import { useState } from "react";
import { Heart, Star, ArrowLeft, Package, ShoppingBag, Check, ChevronRight } from "lucide-react";
import { C, P } from "../constants";
import { Btn } from "../components";
import { PRODUCTS, REVIEWS } from "../data";

export function ProductDetail({ product: p, onBack, onReview }: any) {
  const [tab, setTab] = useState("details");
  const [wl, setWl] = useState(false);
  const sts = [1, 2, 3, 4, 5];
  const rel = PRODUCTS.filter(r => r.cat === p.cat && r.id !== p.id).slice(0, 3);
  return (
    <div style={{ paddingBottom: 80 }}>
      <div style={{ position: "relative" }}><div style={{ height: 280, background: C.soft, display: "flex", alignItems: "center", justifyContent: "center" }}><Package size={48} color={C.muted} strokeWidth={.8} /></div><div style={{ position: "absolute", top: 14, left: P, right: P, display: "flex", justifyContent: "space-between" }}><button onClick={onBack} style={{ width: 36, height: 36, borderRadius: 12, background: "rgba(255,255,255,.85)", backdropFilter: "blur(8px)", border: "none", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" }}><ArrowLeft size={16} color={C.text} /></button><button onClick={() => setWl(!wl)} style={{ width: 36, height: 36, borderRadius: 12, background: "rgba(255,255,255,.85)", backdropFilter: "blur(8px)", border: "none", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" }}><Heart size={16} color={wl ? C.coral : C.sub} fill={wl ? C.coral : "none"} /></button></div></div>
      <div style={{ padding: `16px ${P}px 0` }}><div style={{ fontSize: 10, fontWeight: 700, color: C.purple, textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 3 }}>{p.cat}</div><h1 style={{ fontSize: 20, fontWeight: 900, color: C.text, margin: "0 0 6px" }}>{p.name}</h1>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 14 }}><div style={{ display: "flex", gap: 1 }}>{sts.map(s => (<Star key={s} size={13} color={s <= Math.round(p.rating) ? C.gold : C.light} fill={s <= Math.round(p.rating) ? C.gold : "none"} strokeWidth={1.5} />))}</div><span style={{ fontSize: 12, fontWeight: 700, color: C.text }}>{p.rating}</span><span style={{ fontSize: 11, color: C.muted }}>({p.reviews})</span></div>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }}><span style={{ fontSize: 24, fontWeight: 900, color: C.text }}>€{p.price}</span><Btn small icon={ShoppingBag}>In den Shop</Btn></div>
      </div>
      <div style={{ display: "flex", borderBottom: `1px solid ${C.border}`, padding: `0 ${P}px` }}>{[{ id: "details", l: "Details" }, { id: "reviews", l: `Reviews (${p.reviews})` }, { id: "related", l: "Ähnlich" }].map(t => (<button key={t.id} onClick={() => setTab(t.id)} style={{ flex: 1, padding: "10px 0", background: "none", border: "none", borderBottom: tab === t.id ? `2px solid ${C.purple}` : "2px solid transparent", fontSize: 12, fontWeight: 700, color: tab === t.id ? C.text : C.muted, cursor: "pointer", fontFamily: "inherit" }}>{t.l}</button>))}</div>
      <div style={{ padding: `14px ${P}px` }}>
        {tab === "details" && (<><p style={{ fontSize: 13, color: C.sub, lineHeight: 1.7, margin: "0 0 20px" }}>{p.desc}</p><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6 }}>{p.specs.map((s: string, i: number) => (<div key={i} style={{ padding: "10px 12px", borderRadius: 10, background: C.soft, display: "flex", alignItems: "center", gap: 6 }}><Check size={11} color={C.purple} strokeWidth={2.5} /><span style={{ fontSize: 12, fontWeight: 600, color: C.text }}>{s}</span></div>))}</div><div style={{ marginTop: 20 }}><Btn full onClick={onReview} icon={Star}>Review · +50 pts</Btn></div></>)}
        {tab === "reviews" && (<><div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 20 }}><div style={{ textAlign: "center" }}><div style={{ fontSize: 32, fontWeight: 900, color: C.text, lineHeight: 1 }}>{p.rating}</div><div style={{ display: "flex", gap: 1, marginTop: 3, justifyContent: "center" }}>{sts.map(s => (<Star key={s} size={10} color={s <= Math.round(p.rating) ? C.gold : C.light} fill={s <= Math.round(p.rating) ? C.gold : "none"} strokeWidth={1.5} />))}</div></div><div style={{ flex: 1 }}>{[5, 4, 3, 2, 1].map(s => { const pc = s === 5 ? .58 : s === 4 ? .27 : s === 3 ? .1 : s === 2 ? .03 : .02; return (<div key={s} style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 3 }}><span style={{ fontSize: 10, fontWeight: 600, color: C.muted, width: 10 }}>{s}</span><div style={{ flex: 1, height: 4, borderRadius: 2, background: C.soft }}><div style={{ width: `${pc * 100}%`, height: "100%", borderRadius: 2, background: C.purple }} /></div></div>); })}</div></div>{REVIEWS.map((rv, i) => (<div key={i} style={{ padding: "12px 0", borderBottom: i < REVIEWS.length - 1 ? `1px solid ${C.border}` : "none" }}><div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}><div style={{ width: 28, height: 28, borderRadius: 9, background: C.purple, display: "flex", alignItems: "center", justifyContent: "center" }}><span style={{ fontSize: 10, fontWeight: 900, color: "#fff" }}>{rv.user[0]}</span></div><span style={{ fontSize: 12, fontWeight: 700, color: C.text }}>{rv.user}</span><span style={{ fontSize: 10, color: C.light, marginLeft: "auto" }}>{rv.time}</span></div><p style={{ fontSize: 12, color: C.sub, lineHeight: 1.5, margin: 0 }}>{rv.text}</p></div>))}<div style={{ marginTop: 16 }}><Btn full variant="outline" onClick={onReview} icon={Star}>Review schreiben</Btn></div></>)}
        {tab === "related" && rel.map((rp, i) => (<div key={rp.id} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 0", borderBottom: i < rel.length - 1 ? `1px solid ${C.border}` : "none" }}><div style={{ width: 52, height: 52, borderRadius: 12, background: C.soft, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><Package size={20} color={C.muted} strokeWidth={1.3} /></div><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 700, color: C.text }}>{rp.name}</div><div style={{ fontSize: 12, color: C.sub, marginTop: 2 }}>€{rp.price}</div></div><ChevronRight size={14} color={C.light} /></div>))}
      </div>
    </div>
  );
}
