import { useState } from "react";
import { Heart, MessageCircle, ArrowLeft, Eye, Package, ShoppingBag, Percent } from "lucide-react";
import { C, P } from "../constants";
import { Pill, Cd, Bg } from "../components";
import { PRODUCTS, CREATORS } from "../data";
import { initials, contentTypeColor } from "../utils/helpers";

export function CreatorsScreen() {
  const [sel, setSel] = useState<any>(null);
  const [copied, setCopied] = useState<string | null>(null);
  const [tab, setTab] = useState("content");
  const [liked, setLiked] = useState<any>({});
  const [following, setFollowing] = useState<any>({ 1: true, 2: true });
  const [feedFilter, setFeedFilter] = useState("All");
  const cp = (code: string, e?: any) => { e?.stopPropagation(); setCopied(code); setTimeout(() => setCopied(null), 2000) };
  const tl = (k: string, e: any) => { e.stopPropagation(); setLiked((p: any) => ({ ...p, [k]: !p[k] })) };
  const tf = (id: number, e?: any) => { e?.stopPropagation(); setFollowing((p: any) => ({ ...p, [id]: !p[id] })) };
  const types = ["All", "Tutorial", "Review", "Unboxing", "Vlog", "Q&A"];
  const hasNew = (cr: any) => cr.content.some((c: any) => c.time === "1d" || c.time === "2d" || c.time === "3d");
  const allContent = CREATORS.flatMap(cr => cr.content.map(c => ({ ...c, creator: cr }))).sort((a: any, b: any) => { const o: any = { "1d": 1, "2d": 2, "3d": 3, "4d": 4, "5d": 5, "1w": 7, "2w": 14 }; return (o[a.time] || 99) - (o[b.time] || 99) });
  const feedList = feedFilter === "All" ? allContent : allContent.filter((c: any) => c.type === feedFilter);
  const cmts: any = { "1-0": { u: "Lisa", t: "Routine hat mich verändert!" }, "2-0": { u: "Marie", t: "Genau so machen wir es!" }, "4-0": { u: "Nils", t: "Chaos war zu gut 😂" } };

  if (sel) {
    const picks = PRODUCTS.filter(p => sel.picks.includes(p.id));
    return (
      <div style={{ paddingBottom: 80, position: "relative" }}><Bg v="creators" /><div style={{ position: "relative", zIndex: 1 }}>
        <div style={{ padding: `14px ${P}px 0` }}><button onClick={() => { setSel(null); setTab("content") }} style={{ background: "none", border: "none", cursor: "pointer", display: "flex", alignItems: "center", gap: 5, fontSize: 12, fontWeight: 600, color: C.muted, padding: 0, fontFamily: "inherit" }}><ArrowLeft size={15} /> Zurück</button></div>
        <div style={{ padding: `18px ${P}px 0`, display: "flex", alignItems: "center", gap: 14 }}><div style={{ width: 64, height: 64, borderRadius: 22, background: C.purple, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><span style={{ fontSize: 20, fontWeight: 900, color: "#fff" }}>{initials(sel.name)}</span></div><div style={{ flex: 1 }}><h2 style={{ fontSize: 18, fontWeight: 900, color: C.text, margin: 0 }}>{sel.name}</h2><p style={{ fontSize: 12, color: C.purple, fontWeight: 600, margin: "1px 0" }}>{sel.handle}</p><span style={{ fontSize: 13, fontWeight: 800, color: C.text }}>{sel.followers} <span style={{ fontSize: 10, color: C.muted }}>Followers</span></span></div></div>
        <div style={{ padding: `12px ${P}px 0`, display: "flex", gap: 8 }}><button onClick={(e: any) => tf(sel.id, e)} style={{ flex: 1, padding: "10px 0", borderRadius: 12, border: following[sel.id] ? `1.5px solid ${C.border}` : "none", background: following[sel.id] ? "transparent" : C.purple, color: following[sel.id] ? C.sub : "#fff", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" }}>{following[sel.id] ? "Following" : "Follow"}</button><button onClick={(e: any) => cp(sel.code, e)} style={{ flex: 1, padding: "10px 0", borderRadius: 12, border: "none", background: C.text, color: "#fff", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" }}>{copied === sel.code ? "Copied!" : sel.code + " · " + sel.discount}</button></div>
        <p style={{ fontSize: 12, color: C.sub, padding: `10px ${P}px 0`, lineHeight: 1.5, margin: 0 }}>{sel.bio}</p>
        <div style={{ display: "flex", borderBottom: `1px solid ${C.border}`, padding: `12px ${P}px 0` }}>{["content", "picks"].map(t => (<button key={t} onClick={() => setTab(t)} style={{ flex: 1, padding: "10px 0", background: "none", border: "none", borderBottom: tab === t ? `2px solid ${C.purple}` : "2px solid transparent", fontSize: 12, fontWeight: 700, color: tab === t ? C.text : C.muted, cursor: "pointer", fontFamily: "inherit" }}>{t === "content" ? "Content" : "Picks"} ({t === "content" ? sel.content.length : picks.length})</button>))}</div>
        <div style={{ padding: `14px ${P}px` }}>
          {tab === "content" && sel.content.map((c: any, i: number) => { const k = `${sel.id}-${i}`, prod = c.product ? PRODUCTS.find(p => p.id === c.product) : null, il = liked[k], cm = cmts[k]; return (<Cd key={i} style={{ marginBottom: 10, padding: 0, overflow: "hidden" }}><div style={{ height: 160, background: C.soft, display: "flex", alignItems: "center", justifyContent: "center", position: "relative" }}><Eye size={22} color={C.text} /><div style={{ position: "absolute", top: 10, left: 10, display: "flex", gap: 4 }}><span style={{ fontSize: 9, fontWeight: 800, color: "#fff", background: contentTypeColor(c.type), padding: "3px 8px", borderRadius: 6 }}>{c.type}</span>{c.exclusive && <span style={{ fontSize: 9, fontWeight: 800, color: C.purple, background: "rgba(255,255,255,.9)", padding: "3px 8px", borderRadius: 6 }}>Exklusiv</span>}</div></div>
            <div style={{ padding: "12px 14px" }}><h4 style={{ fontSize: 14, fontWeight: 800, color: C.text, margin: "0 0 4px" }}>{c.title}</h4><p style={{ fontSize: 12, color: C.sub, margin: "0 0 10px", lineHeight: 1.5 }}>{c.desc}</p>
              {prod && <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "8px 10px", borderRadius: 10, background: C.soft, marginBottom: 10 }}><Package size={13} color={C.muted} /><div style={{ flex: 1 }}><div style={{ fontSize: 11, fontWeight: 700, color: C.text }}>{prod.name}</div><div style={{ display: "flex", gap: 4 }}><span style={{ fontSize: 10, color: C.muted, textDecoration: "line-through" }}>€{prod.price}</span><span style={{ fontSize: 10, fontWeight: 800, color: C.purple }}>€{(parseFloat(prod.price) * (1 - parseInt(sel.discount) / 100)).toFixed(2)}</span></div></div><ShoppingBag size={12} color={C.text} /></div>}
              <div style={{ display: "flex", alignItems: "center", gap: 3 }}><button onClick={(e: any) => tl(k, e)} style={{ background: "none", border: "none", cursor: "pointer", display: "flex", alignItems: "center", gap: 3, fontSize: 11, fontWeight: 600, color: il ? C.coral : C.muted, padding: "3px 8px 3px 0" }}><Heart size={14} fill={il ? C.coral : "none"} color={il ? C.coral : C.muted} strokeWidth={1.8} /> {c.likes + (il ? 1 : 0)}</button><span style={{ display: "flex", alignItems: "center", gap: 3, fontSize: 11, color: C.muted, padding: "3px 8px" }}><MessageCircle size={13} strokeWidth={1.8} /> {c.comments}</span></div>
              {cm && <div style={{ marginTop: 8, padding: "8px 10px", borderRadius: 8, background: C.soft, fontSize: 11 }}><span style={{ fontWeight: 700, color: C.text }}>{cm.u}</span> <span style={{ color: C.sub }}>{cm.t}</span></div>}
            </div></Cd>); })}
          {tab === "picks" && picks.map((p, i) => (<div key={p.id} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 0", borderBottom: i < picks.length - 1 ? `1px solid ${C.border}` : "none" }}><div style={{ width: 48, height: 48, borderRadius: 12, background: C.soft, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><Package size={20} color={C.muted} strokeWidth={1.3} /></div><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 700, color: C.text }}>{p.name}</div><div style={{ display: "flex", gap: 5 }}><span style={{ fontSize: 11, color: C.muted, textDecoration: "line-through" }}>€{p.price}</span><span style={{ fontSize: 12, fontWeight: 800, color: C.purple }}>€{(parseFloat(p.price) * (1 - parseInt(sel.discount) / 100)).toFixed(2)}</span></div></div><div style={{ padding: "8px 12px", borderRadius: 8, background: C.text, color: "#fff", fontSize: 11, fontWeight: 700 }}>Shop</div></div>))}
        </div>
      </div></div>
    );
  }
  return (
    <div style={{ paddingBottom: 80, position: "relative" }}><Bg v="creators" /><div style={{ position: "relative", zIndex: 1 }}>
      <div style={{ padding: `24px ${P}px 16px` }}><h1 style={{ fontSize: 22, fontWeight: 900, color: C.text, margin: "0 0 2px" }}>Creators</h1><p style={{ fontSize: 12, color: C.muted, margin: 0 }}>Exklusiver Content</p></div>
      <div style={{ padding: `0 ${P}px 14px` }}><div style={{ display: "flex", gap: 14, overflowX: "auto" }}>{CREATORS.map(cr => { const nw = hasNew(cr); return (<div key={cr.id} onClick={() => setSel(cr)} style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 6, cursor: "pointer", flexShrink: 0 }}><div style={{ width: 56, height: 56, borderRadius: 18, padding: nw ? 2 : 0, background: nw ? `linear-gradient(135deg,${C.purple},${C.coral})` : "transparent" }}><div style={{ width: nw ? 52 : 56, height: nw ? 52 : 56, borderRadius: nw ? 16 : 18, background: C.purple, display: "flex", alignItems: "center", justifyContent: "center", border: nw ? "2px solid #fff" : "none" }}><span style={{ fontSize: 15, fontWeight: 900, color: "#fff" }}>{initials(cr.name)}</span></div></div><span style={{ fontSize: 10, fontWeight: 700, color: C.text, maxWidth: 60, textAlign: "center", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{cr.name}</span></div>); })}</div></div>
      <div style={{ display: "flex", gap: 6, padding: `0 ${P}px 14px`, overflowX: "auto" }}>{types.map(t => (<Pill key={t} active={feedFilter === t} onClick={() => setFeedFilter(t)}>{t}</Pill>))}</div>
      <div style={{ padding: `0 ${P}px`, display: "flex", flexDirection: "column", gap: 14 }}>{feedList.map((c: any, i: number) => { const k = `feed-${c.creator.id}-${i}`, oi = c.creator.content.indexOf(c), prod = c.product ? PRODUCTS.find(p => p.id === c.product) : null, il = liked[k], cm = cmts[`${c.creator.id}-${oi}`]; return (
        <Cd key={k} style={{ padding: 0, overflow: "hidden" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, padding: "12px 14px 0" }}><div onClick={(e: any) => { e.stopPropagation(); setSel(c.creator) }} style={{ width: 32, height: 32, borderRadius: 10, background: C.purple, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0 }}><span style={{ fontSize: 11, fontWeight: 900, color: "#fff" }}>{initials(c.creator.name)}</span></div><div style={{ flex: 1 }} onClick={() => setSel(c.creator)}><span style={{ fontSize: 12, fontWeight: 700, color: C.text, cursor: "pointer" }}>{c.creator.name}</span><br /><span style={{ fontSize: 10, color: C.light }}>{c.time} ago</span></div><div style={{ display: "flex", gap: 4 }}><span style={{ fontSize: 9, fontWeight: 800, color: "#fff", background: contentTypeColor(c.type), padding: "2px 7px", borderRadius: 6 }}>{c.type}</span>{c.exclusive && <span style={{ fontSize: 9, fontWeight: 800, color: C.purple, background: `${C.purple}06`, padding: "2px 7px", borderRadius: 6 }}>Exklusiv</span>}</div></div>
          <div style={{ height: 180, margin: "10px 14px 0", borderRadius: 12, background: C.soft, display: "flex", alignItems: "center", justifyContent: "center" }}><Eye size={20} color={C.text} /></div>
          <div style={{ padding: "12px 14px 14px" }}><h4 style={{ fontSize: 14, fontWeight: 800, color: C.text, margin: "0 0 4px" }}>{c.title}</h4><p style={{ fontSize: 12, color: C.sub, margin: "0 0 10px", lineHeight: 1.5 }}>{c.desc}</p>
            {prod && <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "8px 10px", borderRadius: 10, background: C.soft, marginBottom: 10 }}><Package size={12} color={C.muted} /><div style={{ flex: 1 }}><div style={{ fontSize: 11, fontWeight: 700, color: C.text }}>{prod.name}</div><div style={{ display: "flex", gap: 3 }}><span style={{ fontSize: 10, color: C.muted, textDecoration: "line-through" }}>€{prod.price}</span><span style={{ fontSize: 10, fontWeight: 800, color: C.purple }}>€{(parseFloat(prod.price) * (1 - parseInt(c.creator.discount) / 100)).toFixed(2)}</span></div></div><ShoppingBag size={12} color={C.text} /></div>}
            <div onClick={(e: any) => cp(c.creator.code, e)} style={{ display: "inline-flex", alignItems: "center", gap: 4, padding: "4px 10px", borderRadius: 7, background: `${C.purple}06`, cursor: "pointer", marginBottom: 10 }}><Percent size={10} color={C.purple} /><span style={{ fontSize: 11, fontWeight: 800, color: C.purple }}>{c.creator.code}</span><span style={{ fontSize: 9, color: C.muted }}>· {c.creator.discount}</span>{copied === c.creator.code && <span style={{ fontSize: 9, color: C.purple }}>✓</span>}</div>
            <div style={{ display: "flex", alignItems: "center", gap: 3 }}><button onClick={(e: any) => tl(k, e)} style={{ background: "none", border: "none", cursor: "pointer", display: "flex", alignItems: "center", gap: 3, fontSize: 11, fontWeight: 600, color: il ? C.coral : C.muted, padding: "3px 8px 3px 0" }}><Heart size={14} fill={il ? C.coral : "none"} color={il ? C.coral : C.muted} strokeWidth={1.8} /> {c.likes + (il ? 1 : 0)}</button><span style={{ display: "flex", alignItems: "center", gap: 3, fontSize: 11, color: C.muted, padding: "3px 8px" }}><MessageCircle size={13} strokeWidth={1.8} /> {c.comments}</span>{!following[c.creator.id] && <button onClick={(e: any) => tf(c.creator.id, e)} style={{ marginLeft: "auto", padding: "4px 10px", borderRadius: 7, border: "none", background: C.purple, color: "#fff", fontSize: 10, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" }}>Follow</button>}</div>
            {cm && <div style={{ marginTop: 8, padding: "8px 10px", borderRadius: 8, background: C.soft, fontSize: 11 }}><span style={{ fontWeight: 700, color: C.text }}>{cm.u}</span> <span style={{ color: C.sub }}>{cm.t}</span></div>}
          </div>
        </Cd>); })}</div>
    </div></div>
  );
}
