import { useState } from "react";
import { Star, Share2, Heart, Crown, Lock, Check, Zap, Award, Gift, Calendar, Sparkles, Truck, Percent, ChevronRight } from "lucide-react";
import { C, P } from "../constants";
import { Btn, Ring, Cd, Bg } from "../components";
import { LEVELS, BADGES } from "../data";

export function Profile({ points, onReferral }: any) {
  const lvl = LEVELS.reduce((a, l) => points >= l.min ? l : a, LEVELS[0]);
  const next = LEVELS[LEVELS.indexOf(lvl) + 1];
  const pct = next ? (points - lvl.min) / (next.min - lvl.min) : 1;
  const [tab, setTab] = useState("badges");
  const eb = BADGES.filter(b => b.earned).length;
  const rewards = [{ n: "Free Shipping", c: 300, i: Truck }, { n: "10% Discount", c: 500, i: Percent }, { n: "Mystery Box", c: 1500, i: Gift }, { n: "VIP Event", c: 3000, i: Calendar }, { n: "Brand Dinner", c: 5000, i: Award }];
  const activity = [{ t: "Review geschrieben", pts: "+50", time: "2h", icon: Star }, { t: "Badge: Amplifier", pts: null, time: "1d", icon: Award }, { t: "Produkt geteilt", pts: "+30", time: "2d", icon: Share2 }, { t: "Level Up", pts: null, time: "5d", icon: Zap }];
  const tabs = [{ id: "badges", l: "Badges" }, { id: "rewards", l: "Rewards" }, { id: "activity", l: "Activity" }, { id: "settings", l: "Settings" }];

  return (
    <div style={{ paddingBottom: 80, position: "relative" }}><Bg v="profile" /><div style={{ position: "relative", zIndex: 1 }}>
      <div style={{ padding: `32px ${P}px 0`, display: "flex", alignItems: "center", gap: 16 }}><Ring size={76} sw={5} pct={pct}><div style={{ width: 54, height: 54, borderRadius: 18, background: C.purple, display: "flex", alignItems: "center", justifyContent: "center" }}><Crown size={24} color="#fff" strokeWidth={1.5} /></div></Ring><div style={{ flex: 1 }}><h2 style={{ fontSize: 18, fontWeight: 900, color: C.text, margin: 0 }}>{lvl.name}</h2><div style={{ fontSize: 24, fontWeight: 900, color: C.text, lineHeight: 1 }}>{points} <span style={{ fontSize: 12, fontWeight: 600, color: C.muted }}>pts</span></div>{next && <p style={{ fontSize: 11, color: C.muted, fontWeight: 600, margin: "3px 0 0" }}>{next.min - points} bis {next.name}</p>}</div></div>
      <div style={{ display: "flex", gap: 8, padding: `16px ${P}px 0` }}>{[{ l: "Reviews", v: "4" }, { l: "Badges", v: `${eb}/${BADGES.length}` }, { l: "Streak", v: "3d" }, { l: "Shares", v: "7" }].map((s, i) => (<div key={i} style={{ flex: 1, padding: "10px 6px", borderRadius: 12, background: C.card, boxShadow: C.sh, textAlign: "center" }}><div style={{ fontSize: 16, fontWeight: 900, color: C.text }}>{s.v}</div><div style={{ fontSize: 9, fontWeight: 700, color: C.muted }}>{s.l}</div></div>))}</div>
      <div style={{ display: "flex", borderBottom: `1px solid ${C.border}`, padding: `16px ${P}px 0` }}>{tabs.map(t => (<button key={t.id} onClick={() => setTab(t.id)} style={{ flex: 1, padding: "10px 0", background: "none", border: "none", borderBottom: tab === t.id ? `2px solid ${C.purple}` : "2px solid transparent", fontSize: 12, fontWeight: 700, color: tab === t.id ? C.text : C.muted, cursor: "pointer", fontFamily: "inherit" }}>{t.l}</button>))}</div>
      <div style={{ padding: `14px ${P}px` }}>
        {tab === "badges" && BADGES.map(b => (<div key={b.id} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 0", borderBottom: `1px solid ${C.border}`, opacity: b.earned ? 1 : .4 }}><div style={{ width: 42, height: 42, borderRadius: 12, background: b.earned ? `${C.purple}08` : C.soft, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><b.icon size={18} color={b.earned ? C.purple : C.light} strokeWidth={1.5} /></div><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 700, color: C.text }}>{b.name}</div>{b.earned ? <div style={{ fontSize: 11, color: C.purple, fontWeight: 600 }}>Verdient</div> : <div style={{ fontSize: 11, color: C.muted }}>{b.hint}</div>}</div>{b.earned ? <Check size={16} color={C.purple} /> : <Lock size={13} color={C.light} />}</div>))}
        {tab === "rewards" && (<div style={{ position: "relative", paddingLeft: 16 }}><div style={{ position: "absolute", left: 6, top: 0, bottom: 0, width: 2, background: C.soft, borderRadius: 1 }} /><div style={{ position: "absolute", left: 6, top: 0, width: 2, borderRadius: 1, background: C.purple, height: `${Math.min((points / 5000) * 100, 100)}%` }} />
          {rewards.map((rw, i) => { const ok = points >= rw.c, isN = !ok && (i === 0 || points >= rewards[i - 1].c); return (<div key={i} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 0", position: "relative" }}><div style={{ position: "absolute", left: -12, width: 14, height: 14, borderRadius: 7, background: ok ? C.purple : isN ? C.card : C.soft, border: ok ? "none" : `2px solid ${isN ? C.purple : C.border}`, display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1 }}>{ok && <Check size={8} color="#fff" strokeWidth={3} />}{isN && <div style={{ width: 5, height: 5, borderRadius: 3, background: C.purple }} />}</div><Cd style={{ flex: 1, padding: 12 }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}><div><div style={{ fontSize: 13, fontWeight: 700, color: C.text }}>{rw.n}</div><div style={{ fontSize: 11, color: C.muted }}>{rw.c} pts</div></div>{ok && <Btn small>Einlösen</Btn>}{isN && <span style={{ fontSize: 11, fontWeight: 700, color: C.purple }}>{rw.c - points} pts</span>}{!ok && !isN && <Lock size={13} color={C.light} />}</div></Cd></div>); })}</div>)}
        {tab === "activity" && activity.map((a, i) => { const AI = a.icon; return (<div key={i} style={{ display: "flex", alignItems: "center", gap: 11, padding: "11px 0", borderBottom: i < activity.length - 1 ? `1px solid ${C.border}` : "none" }}><div style={{ width: 34, height: 34, borderRadius: 10, background: C.soft, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><AI size={15} color={C.purple} strokeWidth={1.8} /></div><div style={{ flex: 1 }}><div style={{ fontSize: 12, fontWeight: 600, color: C.text }}>{a.t}</div><div style={{ fontSize: 10, color: C.light }}>{a.time} ago</div></div>{a.pts && <span style={{ fontSize: 12, fontWeight: 800, color: C.purple }}>{a.pts}</span>}</div>); })}
        {tab === "settings" && (<div>{[{ l: "Account", s: "E-Mail, Passwort", i: Crown }, { l: "Freunde einladen", s: "200 pts verdient", i: Gift, action: onReferral }, { l: "Benachrichtigungen", s: "Push, E-Mail", i: Sparkles }, { l: "Partner", s: "Alex · Verbunden", i: Heart }, { l: "Datenschutz", s: "Sichtbarkeit", i: Lock }].map((s, i) => (<div key={i} onClick={s.action || undefined} style={{ display: "flex", alignItems: "center", gap: 11, padding: "12px 0", borderBottom: i < 4 ? `1px solid ${C.border}` : "none", cursor: "pointer" }}><div style={{ width: 34, height: 34, borderRadius: 10, background: C.soft, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><s.i size={15} color={C.sub} strokeWidth={1.6} /></div><div style={{ flex: 1 }}><div style={{ fontSize: 12, fontWeight: 600, color: C.text }}>{s.l}</div><div style={{ fontSize: 11, color: C.muted }}>{s.s}</div></div><ChevronRight size={13} color={C.light} /></div>))}</div>)}
      </div>
    </div></div>
  );
}
