import { useState } from "react";
import { Gift, ArrowLeft, Check, Lock, Send } from "lucide-react";
import { C, P } from "../constants";
import { Btn, Cd, Bg } from "../components";

export function Referral({ onBack }: { onBack: () => void }) {
  const [copied, setCopied] = useState(false);
  const [tab, setTab] = useState("milestones");
  const copy = () => { setCopied(true); setTimeout(() => setCopied(false), 2000) };
  const rws = [{ count: 1, reward: "200 Punkte", done: true }, { count: 3, reward: "500 pts + Shipping", done: false }, { count: 5, reward: "Mystery Box", done: false }, { count: 10, reward: "VIP Status", done: false }];
  const friends = [{ name: "Sophie M.", status: "joined", pts: 200 }, { name: "David K.", status: "pending", pts: 0 }];
  return (
    <div style={{ paddingBottom: 80, position: "relative" }}><Bg v="profile" />
      <div style={{ position: "relative", zIndex: 1 }}>
        <div style={{ padding: `16px ${P}px 0` }}><button onClick={onBack} style={{ background: "none", border: "none", cursor: "pointer", display: "flex", alignItems: "center", gap: 5, fontSize: 12, fontWeight: 600, color: C.muted, padding: 0, fontFamily: "inherit" }}><ArrowLeft size={15} /> Zurück</button></div>
        <div style={{ padding: `24px ${P}px 0`, textAlign: "center" }}><div style={{ width: 72, height: 72, borderRadius: 24, background: `${C.purple}08`, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 16px" }}><Gift size={32} color={C.purple} strokeWidth={1.3} /></div><h1 style={{ fontSize: 22, fontWeight: 900, color: C.text, margin: "0 0 6px" }}>Freunde einladen</h1><p style={{ fontSize: 13, color: C.sub, margin: "0 0 20px" }}>Ihr bekommt <span style={{ fontWeight: 800, color: C.purple }}>beide 200 Punkte</span></p></div>
        <div style={{ padding: `0 ${P}px` }}><Cd style={{ padding: 0, overflow: "hidden", marginBottom: 16 }}><div style={{ padding: "14px 16px" }}><div style={{ fontSize: 10, fontWeight: 700, color: C.muted, textTransform: "uppercase", letterSpacing: ".05em", marginBottom: 8 }}>Dein Code</div><div style={{ display: "flex", gap: 8 }}><div style={{ flex: 1, padding: "12px 14px", borderRadius: 10, background: C.soft, fontSize: 16, fontWeight: 900, color: C.purple, letterSpacing: ".06em", textAlign: "center" }}>CIRCLE-X7K9</div><button onClick={copy} style={{ padding: "12px 16px", borderRadius: 10, border: "none", background: copied ? C.purple : C.text, color: "#fff", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" }}>{copied ? "✓" : "Kopieren"}</button></div></div>
          <div style={{ padding: "0 16px 14px" }}><div style={{ display: "flex", gap: 6 }}>{["WhatsApp", "SMS", "E-Mail", "Mehr"].map((ch, i) => (<button key={i} style={{ flex: 1, padding: "10px 0", borderRadius: 10, border: "none", background: C.soft, color: C.sub, fontSize: 10, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" }}>{ch}</button>))}</div></div>
        </Cd></div>
        <div style={{ display: "flex", borderBottom: `1px solid ${C.border}`, padding: `0 ${P}px` }}>{[{ id: "milestones", l: "Meilensteine" }, { id: "friends", l: `Freunde (${friends.length})` }].map(t => (<button key={t.id} onClick={() => setTab(t.id)} style={{ flex: 1, padding: "10px 0", background: "none", border: "none", borderBottom: tab === t.id ? `2px solid ${C.purple}` : "2px solid transparent", fontSize: 12, fontWeight: 700, color: tab === t.id ? C.text : C.muted, cursor: "pointer", fontFamily: "inherit" }}>{t.l}</button>))}</div>
        <div style={{ padding: `14px ${P}px` }}>
          {tab === "milestones" && (<div style={{ position: "relative", paddingLeft: 16 }}><div style={{ position: "absolute", left: 6, top: 0, bottom: 0, width: 2, background: C.soft, borderRadius: 1 }} /><div style={{ position: "absolute", left: 6, top: 0, width: 2, borderRadius: 1, background: C.purple, height: "25%" }} />
            {rws.map((rw, i) => { const ok = rw.done, isN = !ok && (i === 0 || rws[i - 1].done); return (<div key={i} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 0", position: "relative" }}><div style={{ position: "absolute", left: -12, width: 14, height: 14, borderRadius: 7, background: ok ? C.purple : isN ? C.card : C.soft, border: ok ? "none" : `2px solid ${isN ? C.purple : C.border}`, display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1 }}>{ok && <Check size={8} color="#fff" strokeWidth={3} />}{isN && <div style={{ width: 5, height: 5, borderRadius: 3, background: C.purple }} />}</div><Cd style={{ flex: 1, padding: 12 }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}><div><div style={{ fontSize: 13, fontWeight: 700, color: C.text }}>{rw.count} {rw.count === 1 ? "Freund" : "Freunde"}</div><div style={{ fontSize: 11, color: C.muted, marginTop: 1 }}>{rw.reward}</div></div>{ok && <Check size={16} color={C.purple} />}{isN && <span style={{ fontSize: 11, fontWeight: 700, color: C.purple }}>Nächstes</span>}{!ok && !isN && <Lock size={13} color={C.light} />}</div></Cd></div>); })}
          </div>)}
          {tab === "friends" && (<>{friends.map((r, i) => (<div key={i} style={{ display: "flex", alignItems: "center", gap: 11, padding: "12px 0", borderBottom: i < friends.length - 1 ? `1px solid ${C.border}` : "none" }}><div style={{ width: 36, height: 36, borderRadius: 11, background: r.status === "joined" ? `${C.purple}08` : C.soft, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><span style={{ fontSize: 13, fontWeight: 900, color: r.status === "joined" ? C.purple : C.muted }}>{r.name[0]}</span></div><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 700, color: C.text }}>{r.name}</div><div style={{ fontSize: 11, color: C.muted }}>{r.status === "joined" ? `+${r.pts} pts` : "Ausstehend"}</div></div>{r.status === "joined" ? <Check size={16} color={C.purple} /> : <span style={{ fontSize: 10, fontWeight: 700, color: C.gold, background: `${C.gold}10`, padding: "3px 8px", borderRadius: 5 }}>Pending</span>}</div>))}<div style={{ marginTop: 16 }}><Btn full icon={Send} onClick={copy}>Weitere einladen</Btn></div></>)}
        </div>
      </div>
    </div>
  );
}
