import { useState, useEffect } from "react";
import { Heart, Star, Share2, Gift, MessageCircle, Sparkles, ChevronRight, Send, Crown, Flame, Calendar, Lock, Check, Plus, Eye, Zap, Award, Package, Percent, Truck, Camera, UserPlus, Globe, ShoppingBag, Search, X, ArrowLeft } from "lucide-react";

const C={bg:"#FAFAF8",card:"#FFFFFF",soft:"#F4F3F0",border:"rgba(0,0,0,0.04)",text:"#1A1A2E",sub:"#6B6B7B",muted:"#A8A8B8",light:"#D0D0DA",purple:"#452861",coral:"#E87C6C",gold:"#D4A840",sh:"0 1px 3px rgba(0,0,0,0.04)"};
const P=18;

const PRODUCTS=[
{id:1,name:"Bloom G-Punkt-Vibrator",price:"24.95",cat:"Vibratoren",desc:"Geschwungener G-Punkt-Vibrator mit 3 Modi. Wasserdicht, wiederaufladbar.",specs:["Silikon & ABS","Wasserdicht IP57","14 cm","90 Min"],rating:4.3,reviews:47},
{id:2,name:"Velvet Touch Blindfold",price:"22.95",cat:"Accessories",desc:"Luxuriöse Augenmaske. Verstellbar und lichtdicht.",specs:["Satin","Verstellbar","Lichtdicht","Handwäsche"],rating:4.7,reviews:31},
{id:3,name:"Botanical Massage Oil",price:"19.95",cat:"Wellness",desc:"Natürliches Massageöl mit Jojoba und Arganöl.",specs:["100ml","Vegan","Ohne Parabene","Natürlich"],rating:4.5,reviews:63},
{id:4,name:"Intimacy Card Game",price:"24.95",cat:"Games",desc:"50 Karten für Paare. Von sanft bis abenteuerlich.",specs:["50 Karten","3 Stufen","Für 2","Ab 18"],rating:4.8,reviews:89},
{id:5,name:"Midnight Silk Robe",price:"54.95",cat:"Lifestyle",desc:"Eleganter Kimono aus fließendem Satin.",specs:["Satin","Einheitsgröße","Waschbar","Mit Gürtel"],rating:4.4,reviews:22},
{id:6,name:"Aromatic Bath Ritual Set",price:"34.95",cat:"Wellness",desc:"Baderitual mit Badebombe, Kerze und Öl.",specs:["3-teilig","Natürlich","Vegan","Geschenkbox"],rating:4.6,reviews:38},
{id:7,name:"Couples Wellness Box",price:"79.95",cat:"Boxes",desc:"Kuratierte Box für Paare mit Überraschungen.",specs:["5+ Produkte","Kuratiert","Geschenkbox","Anleitung"],rating:4.9,reviews:54},
{id:8,name:"Explorer Mystery Box",price:"49.95",cat:"Boxes",desc:"Handverlesene Produkte im Wert von mind. €80.",specs:["3-4 Produkte","Wert €80+","Überraschung","Diskret"],rating:4.2,reviews:41},
];
const LEVELS=[{name:"Curious",min:0},{name:"Explorer",min:500},{name:"Connoisseur",min:2000},{name:"Ambassador",min:5000}];
const BADGES=[{id:"review",name:"First Voice",icon:MessageCircle,earned:true,hint:null},{id:"social",name:"Amplifier",icon:Share2,earned:true,hint:null},{id:"couple",name:"Power Couple",icon:Heart,earned:false,hint:"Partner verknüpfen"},{id:"explorer",name:"Explorer",icon:Globe,earned:false,hint:"3 Kategorien"},{id:"streak",name:"On Fire",icon:Flame,earned:false,hint:"7 Tage aktiv"},{id:"referral",name:"Matchmaker",icon:UserPlus,earned:false,hint:"1 Freund einladen"}];
const DISCUSSIONS=[{id:1,title:"First time buying — what do you recommend?",replies:14,likes:32,time:"2h",topic:"Beginners",hot:true},{id:2,title:"Best couples game for a long-term relationship?",replies:23,likes:51,time:"4h",topic:"Couples",hot:true},{id:3,title:"Massage oil vs massage candle?",replies:8,likes:19,time:"6h",topic:"Wellness"},{id:4,title:"How to talk to your partner about trying new things",replies:31,likes:67,time:"8h",topic:"Tips",hot:true},{id:5,title:"Mystery Box — was it worth it?",replies:17,likes:28,time:"12h",topic:"Products"},{id:6,title:"Is it normal to feel nervous?",replies:42,likes:89,time:"1d",topic:"Beginners",hot:true},{id:7,title:"Self-care routines that work",replies:11,likes:24,time:"1d",topic:"Wellness"}];
const CREATORS=[
{id:1,name:"Lena M.",handle:"@lena.glow",bio:"Wellness & self-care",followers:"48K",code:"LENA15",discount:"15%",picks:[1,3,6],content:[{title:"My Evening Self-Care Ritual",type:"Tutorial",desc:"Step by step wind-down routine.",likes:284,comments:42,time:"2d",exclusive:true,product:1},{title:"Why Botanical Oil",type:"Review",desc:"3 weeks daily use — honest thoughts.",likes:156,comments:19,time:"5d",exclusive:true,product:3}]},
{id:2,name:"Tom & Julia",handle:"@tomjulia",bio:"Date night inspo",followers:"112K",code:"COUPLE20",discount:"20%",picks:[4,7,2],content:[{title:"Date Night In",type:"Vlog",desc:"Cooking + Intimacy Card Game.",likes:512,comments:87,time:"3d",exclusive:true,product:4},{title:"Card Game Review",type:"Review",desc:"6 years and still surprised.",likes:389,comments:64,time:"1w",exclusive:true,product:4}]},
{id:3,name:"Sara K.",handle:"@sara.rituals",bio:"Mindful living",followers:"67K",code:"SARA10",discount:"10%",picks:[3,5,6,1],content:[{title:"3 Ways to Use Massage Oil",type:"Tutorial",desc:"Shoulder, hand and full body.",likes:198,comments:33,time:"4d",exclusive:true,product:3}]},
{id:4,name:"Max & Nora",handle:"@maxnora",bio:"Curiosity & fun",followers:"89K",code:"EXPLORE25",discount:"25%",picks:[8,4,7,2],content:[{title:"Mystery Box Challenge!",type:"Unboxing",desc:"Blind rating every item.",likes:445,comments:72,time:"1d",exclusive:true,product:8},{title:"Our Honest Top 3",type:"Review",desc:"The ones we keep reordering.",likes:312,comments:51,time:"5d",product:null}]},
];
const NOTIFS=[{id:1,type:"match",title:"It's a Match!",body:"Alex hat auch die Card Game gewählt",time:"12m",read:false,go:"couple"},{id:2,type:"creator",title:"Neuer Content",body:"Max & Nora: Mystery Box!",time:"1h",read:false,go:"creators"},{id:3,type:"points",title:"+50 Punkte",body:"Review veröffentlicht",time:"3h",read:false,go:"earn"},{id:4,type:"community",title:"Antwort erhalten",body:"Lisa: Toller Tipp!",time:"5h",read:true,go:"community"},{id:5,type:"challenge",title:"Fast geschafft!",body:"2 Reviews für +300 pts",time:"8h",read:true,go:"earn"},{id:6,type:"event",title:"Event Reminder",body:"Workshop in 5 Tagen",time:"2d",read:true,go:"events"}];

const RV=[{user:"Marie K.",rating:5,text:"Absolut begeistert! Qualität top.",time:"3d",helpful:12},{user:"Anna S.",rating:4,text:"Erfüllt seinen Zweck, schön.",time:"1w",helpful:8},{user:"Laura B.",rating:5,text:"Perfektes Geschenk. Diskret.",time:"2w",helpful:5}];
const ni=t=>t==="match"?Heart:t==="creator"?Camera:t==="points"?Star:t==="community"?MessageCircle:t==="challenge"?Zap:t==="event"?Calendar:Sparkles;
const nc=t=>t==="match"?C.coral:t==="creator"?C.purple:t==="points"?C.gold:t==="community"?"#3B6BB5":t==="challenge"?"#C4702B":t==="event"?"#2D7D6B":C.sub;
const tc=t=>t==="Beginners"?"#2D7D6B":t==="Couples"?C.coral:t==="Wellness"?C.purple:t==="Products"?"#C4702B":t==="Tips"?"#3B6BB5":C.sub;
const tcc=t=>t==="Tutorial"?C.purple:t==="Review"?"#2D7D6B":t==="Unboxing"?"#C4702B":t==="Q&A"?"#3B6BB5":C.sub;
const ini=n=>n.split(" ").map(w=>w[0]).join("").slice(0,2);

function Pill({children,active,onClick}){
  return (<button onClick={onClick} style={{padding:"6px 14px",borderRadius:20,border:`1.5px solid ${active?C.purple:C.border}`,background:active?C.purple:C.bg,color:active?"#fff":C.sub,fontSize:11,fontWeight:700,cursor:"pointer",whiteSpace:"nowrap",fontFamily:"inherit"}}>{children}</button>);
}
function Btn({children,onClick,disabled,full,variant="dark",small,icon:I}){
  const bg=variant==="dark"?C.text:variant==="outline"?"transparent":C.soft;
  const cl=variant==="dark"?"#fff":C.text;
  return (<button onClick={onClick} disabled={disabled} style={{padding:small?"8px 16px":"12px 22px",borderRadius:14,border:variant==="outline"?`1.5px solid ${C.border}`:"none",background:bg,color:cl,fontSize:small?12:14,fontWeight:700,cursor:disabled?"default":"pointer",opacity:disabled?.25:1,width:full?"100%":"auto",display:"inline-flex",alignItems:"center",justifyContent:"center",gap:7,fontFamily:"inherit"}}>{I&&<I size={small?13:15} strokeWidth={2.2}/>}{children}</button>);
}
function Ring({size,sw,pct,color=C.purple,children}){
  const r=(size-sw)/2,ci=2*Math.PI*r;
  return (<div style={{position:"relative",width:size,height:size}}><svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={C.soft} strokeWidth={sw}/><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth={sw} strokeDasharray={ci} strokeDashoffset={ci*(1-pct)} strokeLinecap="round" transform={`rotate(-90 ${size/2} ${size/2})`} style={{transition:"stroke-dashoffset .8s ease"}}/></svg><div style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center"}}>{children}</div></div>);
}
function Cd({children,style:s,...p}){return (<div style={{padding:16,borderRadius:16,background:C.card,boxShadow:C.sh,...s}} {...p}>{children}</div>);}
function Anim({show,amount,onDone}){
  useEffect(()=>{if(show){const t=setTimeout(onDone,1400);return ()=>clearTimeout(t)}},[show]);
  if(!show) return null;
  return (<div style={{position:"fixed",inset:0,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(250,250,248,.94)",backdropFilter:"blur(16px)",zIndex:300,animation:"fi .15s"}}><div style={{textAlign:"center",animation:"pop .3s cubic-bezier(.34,1.56,.64,1)"}}><div style={{fontSize:48,fontWeight:900,color:C.text}}>+{amount}</div><div style={{fontSize:13,color:C.muted,fontWeight:600,marginTop:2}}>Punkte</div></div></div>);
}
function Nav({active,go}){
  return (<nav style={{position:"fixed",bottom:0,left:"50%",transform:"translateX(-50%)",width:"100%",maxWidth:430,background:"rgba(255,255,255,.92)",backdropFilter:"blur(20px)",borderTop:`1px solid ${C.border}`,display:"flex",justifyContent:"space-around",padding:"8px 0 24px",zIndex:100}}>{[{id:"home",i:Sparkles},{id:"earn",i:Star},{id:"couple",i:Heart},{id:"community",i:MessageCircle},{id:"creators",i:Camera},{id:"profile",i:Crown}].map(t=>(<button key={t.id} onClick={()=>go(t.id)} style={{background:"none",border:"none",cursor:"pointer",padding:"4px 6px",position:"relative"}}><t.i size={20} color={active===t.id?C.purple:C.muted} fill={active===t.id?C.purple:"none"} strokeWidth={active===t.id?2.2:1.4}/>{active===t.id&&<div style={{position:"absolute",top:-3,left:"50%",transform:"translateX(-50%)",width:4,height:4,borderRadius:2,background:C.purple}}/>}</button>))}</nav>);
}
function Bg({v="home"}){
  const w={position:"absolute",inset:0,overflow:"hidden",pointerEvents:"none",zIndex:0};
  if(v==="home") return (<div style={w}><svg viewBox="0 0 430 1200" fill="none" style={{position:"absolute",top:0,left:0,width:"100%",height:"100%"}}><path d="M-80 -40Q180 -40 280 140Q260 300 60 320Q-80 340-100 180Z" fill={C.purple} opacity=".05"/><circle cx="400" cy="90" r="120" fill={C.purple} opacity=".035"/><path d="M430 380Q340 460 300 580Q380 700 430 660Z" fill={C.purple} opacity=".03"/><circle cx="40" cy="850" r="90" fill={C.purple} opacity=".025"/></svg></div>);
  if(v==="earn") return (<div style={w}><svg viewBox="0 0 430 1200" fill="none" style={{position:"absolute",top:0,left:0,width:"100%",height:"100%"}}><path d="M320-40Q450-40 450 100Q450 240 320 220Q220 200 270 60Z" fill={C.purple} opacity=".045"/><circle cx="30" cy="500" r="100" fill={C.purple} opacity=".03"/><circle cx="400" cy="900" r="70" fill={C.purple} opacity=".025"/></svg></div>);
  if(v==="couple") return (<div style={w}><svg viewBox="0 0 430 900" fill="none" style={{position:"absolute",top:0,left:0,width:"100%",height:"100%"}}><path d="M-40-40Q200-40 220 80Q240 200 100 240Q-40 280-40 140Z" fill={C.purple} opacity=".04"/><circle cx="390" cy="150" r="90" fill={C.purple} opacity=".04"/><path d="M430 480Q360 400 340 300Q420 250 430 320Z" fill={C.purple} opacity=".03"/></svg></div>);
  if(v==="community") return (<div style={w}><svg viewBox="0 0 430 900" fill="none" style={{position:"absolute",top:0,left:0,width:"100%",height:"100%"}}><path d="M300-40Q460-40 460 100Q460 220 360 200Q260 180 280 40Z" fill={C.purple} opacity=".045"/><path d="M-60 460Q120 410 220 540Q200 720 30 690Q-60 680-60 580Z" fill={C.purple} opacity=".03"/><circle cx="410" cy="400" r="40" fill={C.purple} opacity=".025"/></svg></div>);
  if(v==="creators") return (<div style={w}><svg viewBox="0 0 430 1200" fill="none" style={{position:"absolute",top:0,left:0,width:"100%",height:"100%"}}><circle cx="380" cy="70" r="130" fill={C.purple} opacity=".04"/><path d="M-60 380Q100 330 200 460Q180 620 30 590Q-60 580-60 480Z" fill={C.purple} opacity=".03"/><circle cx="410" cy="850" r="60" fill={C.purple} opacity=".02"/></svg></div>);
  if(v==="profile") return (<div style={w}><svg viewBox="0 0 430 900" fill="none" style={{position:"absolute",top:0,left:0,width:"100%",height:"100%"}}><path d="M40-40Q320-40 400 60Q460 180 340 260Q200 320 60 260Q-40 200-40 60Z" fill={C.purple} opacity=".045"/><circle cx="50" cy="520" r="60" fill={C.purple} opacity=".03"/><path d="M430 460Q430 620 360 700Q280 660 320 540Q360 440 430 460Z" fill={C.purple} opacity=".025"/></svg></div>);
  return (<div style={w}><svg viewBox="0 0 430 900" fill="none" style={{position:"absolute",top:0,left:0,width:"100%",height:"100%"}}><circle cx="380" cy="80" r="110" fill={C.purple} opacity=".035"/><circle cx="40" cy="500" r="80" fill={C.purple} opacity=".025"/></svg></div>);
}

function Onboarding({onDone}){
  const[step,setStep]=useState(0);
  const steps=[{icon:Sparkles,color:C.purple,title:"Willkommen bei Circle",desc:"Dein Loyalty-Programm für mehr Spaß am Liebesleben."},{icon:Star,color:C.gold,title:"Sammle Punkte",desc:"Reviews, Shares und Challenges — je aktiver, desto mehr Rewards."},{icon:Heart,color:C.coral,title:"Entdeckt gemeinsam",desc:"Wählt getrennt Produkte. Gleiches gewählt? Match!"},{icon:Crown,color:C.purple,title:"Bereit?",desc:"Steige auf, sammle Badges, werde Ambassador."}];
  const s=steps[step],last=step===3,SI=s.icon;
  return (
    <div style={{minHeight:"100vh",background:C.bg,display:"flex",flexDirection:"column"}}>
      <div style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"0 36px"}}>
        <div key={step} style={{animation:"fi .25s",display:"flex",flexDirection:"column",alignItems:"center"}}>
          <div style={{width:88,height:88,borderRadius:30,background:`${s.color}08`,display:"flex",alignItems:"center",justifyContent:"center",marginBottom:28}}><SI size={40} color={s.color} strokeWidth={1.3} fill={step===2?s.color:"none"}/></div>
          <h1 style={{fontSize:24,fontWeight:900,color:C.text,textAlign:"center",margin:"0 0 12px",lineHeight:1.25}}>{s.title}</h1>
          <p style={{fontSize:14,color:C.sub,textAlign:"center",lineHeight:1.7,margin:0,maxWidth:280}}>{s.desc}</p>
        </div>
      </div>
      <div style={{padding:"0 32px 56px"}}>
        <div style={{display:"flex",justifyContent:"center",gap:6,marginBottom:24}}>{steps.map((_,i)=>(<div key={i} style={{width:i===step?20:6,height:6,borderRadius:3,background:i===step?C.purple:C.soft,transition:"all .3s"}}/>))}</div>
        <Btn full onClick={()=>last?onDone():setStep(step+1)}>{last?"Let's go":"Weiter"}</Btn>
        {!last&&<button onClick={onDone} style={{width:"100%",padding:"12px 0",marginTop:8,background:"none",border:"none",fontSize:13,fontWeight:600,color:C.muted,cursor:"pointer",fontFamily:"inherit"}}>Überspringen</button>}
      </div>
    </div>
  );
}

function NotifPanel({open,onClose,onNav}){
  const[notifs,setNotifs]=useState(NOTIFS);const[filter,setFilter]=useState("all");
  const ur=notifs.filter(n=>!n.read).length;
  const fl=filter==="all"?notifs:filter==="unread"?notifs.filter(n=>!n.read):notifs.filter(n=>n.type===filter);
  if(!open) return null;
  return (
    <div style={{position:"fixed",inset:0,zIndex:250,background:C.bg,display:"flex",flexDirection:"column",animation:"fi .15s"}}>
      <div style={{padding:`18px ${P}px 0`}}>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14}}><h1 style={{fontSize:22,fontWeight:900,color:C.text,margin:0}}>Mitteilungen</h1><button onClick={onClose} style={{background:"none",border:"none",cursor:"pointer"}}><X size={20} color={C.sub}/></button></div>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:12}}>
          <div style={{display:"flex",gap:6}}>{[{id:"all",l:"Alle"},{id:"unread",l:`Neu (${ur})`},{id:"match",l:"Matches"}].map(f=>(<Pill key={f.id} active={filter===f.id} onClick={()=>setFilter(f.id)}>{f.l}</Pill>))}</div>
          {ur>0&&<button onClick={()=>setNotifs(p=>p.map(n=>({...n,read:true})))} style={{background:"none",border:"none",cursor:"pointer",fontSize:12,fontWeight:700,color:C.purple,fontFamily:"inherit"}}>Alle lesen</button>}
        </div>
      </div>
      <div style={{flex:1,overflowY:"auto",padding:`0 ${P}px 32px`}}>
        {fl.length===0&&<div style={{textAlign:"center",padding:"50px 0"}}><Check size={22} color={C.muted}/><p style={{fontSize:13,color:C.muted,marginTop:8}}>Alles gelesen</p></div>}
        {fl.map((n,i)=>{const NI=ni(n.type); return (
          <div key={n.id} onClick={()=>{setNotifs(p=>p.map(x=>x.id===n.id?{...x,read:true}:x));onNav(n.go);onClose()}} style={{display:"flex",gap:11,padding:"13px 0",borderBottom:i<fl.length-1?`1px solid ${C.border}`:"none",cursor:"pointer",opacity:n.read?.5:1}}>
            <div style={{width:38,height:38,borderRadius:12,background:`${nc(n.type)}08`,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,position:"relative"}}><NI size={16} color={nc(n.type)} strokeWidth={1.8} fill={n.type==="match"?nc(n.type):"none"}/>{!n.read&&<div style={{position:"absolute",top:-2,right:-2,width:8,height:8,borderRadius:4,background:C.purple,border:"2px solid #fff"}}/>}</div>
            <div style={{flex:1,minWidth:0}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:1}}><span style={{fontSize:13,fontWeight:n.read?600:800,color:C.text}}>{n.title}</span><span style={{fontSize:10,color:C.light}}>{n.time}</span></div><p style={{fontSize:12,color:C.sub,margin:0,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{n.body}</p></div>
          </div>);
        })}
      </div>
    </div>
  );
}

function ProductDetail({product:p,onBack,onReview}){
  const[tab,setTab]=useState("details");const[wl,setWl]=useState(false);const sts=[1,2,3,4,5];const rel=PRODUCTS.filter(r=>r.cat===p.cat&&r.id!==p.id).slice(0,3);
  return (
    <div style={{paddingBottom:80}}>
      <div style={{position:"relative"}}><div style={{height:280,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center"}}><Package size={48} color={C.muted} strokeWidth={.8}/></div><div style={{position:"absolute",top:14,left:P,right:P,display:"flex",justifyContent:"space-between"}}><button onClick={onBack} style={{width:36,height:36,borderRadius:12,background:"rgba(255,255,255,.85)",backdropFilter:"blur(8px)",border:"none",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><ArrowLeft size={16} color={C.text}/></button><button onClick={()=>setWl(!wl)} style={{width:36,height:36,borderRadius:12,background:"rgba(255,255,255,.85)",backdropFilter:"blur(8px)",border:"none",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><Heart size={16} color={wl?C.coral:C.sub} fill={wl?C.coral:"none"}/></button></div></div>
      <div style={{padding:`16px ${P}px 0`}}><div style={{fontSize:10,fontWeight:700,color:C.purple,textTransform:"uppercase",letterSpacing:".06em",marginBottom:3}}>{p.cat}</div><h1 style={{fontSize:20,fontWeight:900,color:C.text,margin:"0 0 6px"}}>{p.name}</h1>
        <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:14}}><div style={{display:"flex",gap:1}}>{sts.map(s=>(<Star key={s} size={13} color={s<=Math.round(p.rating)?C.gold:C.light} fill={s<=Math.round(p.rating)?C.gold:"none"} strokeWidth={1.5}/>))}</div><span style={{fontSize:12,fontWeight:700,color:C.text}}>{p.rating}</span><span style={{fontSize:11,color:C.muted}}>({p.reviews})</span></div>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:16}}><span style={{fontSize:24,fontWeight:900,color:C.text}}>€{p.price}</span><Btn small icon={ShoppingBag}>In den Shop</Btn></div>
      </div>
      <div style={{display:"flex",borderBottom:`1px solid ${C.border}`,padding:`0 ${P}px`}}>{[{id:"details",l:"Details"},{id:"reviews",l:`Reviews (${p.reviews})`},{id:"related",l:"Ähnlich"}].map(t=>(<button key={t.id} onClick={()=>setTab(t.id)} style={{flex:1,padding:"10px 0",background:"none",border:"none",borderBottom:tab===t.id?`2px solid ${C.purple}`:"2px solid transparent",fontSize:12,fontWeight:700,color:tab===t.id?C.text:C.muted,cursor:"pointer",fontFamily:"inherit"}}>{t.l}</button>))}</div>
      <div style={{padding:`14px ${P}px`}}>
        {tab==="details"&&(<><p style={{fontSize:13,color:C.sub,lineHeight:1.7,margin:"0 0 20px"}}>{p.desc}</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}>{p.specs.map((s,i)=>(<div key={i} style={{padding:"10px 12px",borderRadius:10,background:C.soft,display:"flex",alignItems:"center",gap:6}}><Check size={11} color={C.purple} strokeWidth={2.5}/><span style={{fontSize:12,fontWeight:600,color:C.text}}>{s}</span></div>))}</div><div style={{marginTop:20}}><Btn full onClick={onReview} icon={Star}>Review · +50 pts</Btn></div></>)}
        {tab==="reviews"&&(<><div style={{display:"flex",alignItems:"center",gap:14,marginBottom:20}}><div style={{textAlign:"center"}}><div style={{fontSize:32,fontWeight:900,color:C.text,lineHeight:1}}>{p.rating}</div><div style={{display:"flex",gap:1,marginTop:3,justifyContent:"center"}}>{sts.map(s=>(<Star key={s} size={10} color={s<=Math.round(p.rating)?C.gold:C.light} fill={s<=Math.round(p.rating)?C.gold:"none"} strokeWidth={1.5}/>))}</div></div><div style={{flex:1}}>{[5,4,3,2,1].map(s=>{const pc=s===5?.58:s===4?.27:s===3?.1:s===2?.03:.02; return (<div key={s} style={{display:"flex",alignItems:"center",gap:6,marginBottom:3}}><span style={{fontSize:10,fontWeight:600,color:C.muted,width:10}}>{s}</span><div style={{flex:1,height:4,borderRadius:2,background:C.soft}}><div style={{width:`${pc*100}%`,height:"100%",borderRadius:2,background:C.purple}}/></div></div>);})}</div></div>{RV.map((rv,i)=>(<div key={i} style={{padding:"12px 0",borderBottom:i<RV.length-1?`1px solid ${C.border}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6}}><div style={{width:28,height:28,borderRadius:9,background:C.purple,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:10,fontWeight:900,color:"#fff"}}>{rv.user[0]}</span></div><span style={{fontSize:12,fontWeight:700,color:C.text}}>{rv.user}</span><span style={{fontSize:10,color:C.light,marginLeft:"auto"}}>{rv.time}</span></div><p style={{fontSize:12,color:C.sub,lineHeight:1.5,margin:0}}>{rv.text}</p></div>))}<div style={{marginTop:16}}><Btn full variant="outline" onClick={onReview} icon={Star}>Review schreiben</Btn></div></>)}
        {tab==="related"&&rel.map((rp,i)=>(<div key={rp.id} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 0",borderBottom:i<rel.length-1?`1px solid ${C.border}`:"none"}}><div style={{width:52,height:52,borderRadius:12,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><Package size={20} color={C.muted} strokeWidth={1.3}/></div><div style={{flex:1}}><div style={{fontSize:13,fontWeight:700,color:C.text}}>{rp.name}</div><div style={{fontSize:12,color:C.sub,marginTop:2}}>€{rp.price}</div></div><ChevronRight size={14} color={C.light}/></div>))}
      </div>
    </div>
  );
}

function Referral({onBack}){
  const[copied,setCopied]=useState(false);const[tab,setTab]=useState("milestones");
  const copy=()=>{setCopied(true);setTimeout(()=>setCopied(false),2000)};
  const rws=[{count:1,reward:"200 Punkte",done:true},{count:3,reward:"500 pts + Shipping",done:false},{count:5,reward:"Mystery Box",done:false},{count:10,reward:"VIP Status",done:false}];
  const friends=[{name:"Sophie M.",status:"joined",pts:200},{name:"David K.",status:"pending",pts:0}];
  return (
    <div style={{paddingBottom:80,position:"relative"}}><Bg v="profile"/>
      <div style={{position:"relative",zIndex:1}}>
        <div style={{padding:`16px ${P}px 0`}}><button onClick={onBack} style={{background:"none",border:"none",cursor:"pointer",display:"flex",alignItems:"center",gap:5,fontSize:12,fontWeight:600,color:C.muted,padding:0,fontFamily:"inherit"}}><ArrowLeft size={15}/> Zurück</button></div>
        <div style={{padding:`24px ${P}px 0`,textAlign:"center"}}><div style={{width:72,height:72,borderRadius:24,background:`${C.purple}08`,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px"}}><Gift size={32} color={C.purple} strokeWidth={1.3}/></div><h1 style={{fontSize:22,fontWeight:900,color:C.text,margin:"0 0 6px"}}>Freunde einladen</h1><p style={{fontSize:13,color:C.sub,margin:"0 0 20px"}}>Ihr bekommt <span style={{fontWeight:800,color:C.purple}}>beide 200 Punkte</span></p></div>
        <div style={{padding:`0 ${P}px`}}><Cd style={{padding:0,overflow:"hidden",marginBottom:16}}><div style={{padding:"14px 16px"}}><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:".05em",marginBottom:8}}>Dein Code</div><div style={{display:"flex",gap:8}}><div style={{flex:1,padding:"12px 14px",borderRadius:10,background:C.soft,fontSize:16,fontWeight:900,color:C.purple,letterSpacing:".06em",textAlign:"center"}}>CIRCLE-X7K9</div><button onClick={copy} style={{padding:"12px 16px",borderRadius:10,border:"none",background:copied?C.purple:C.text,color:"#fff",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>{copied?"✓":"Kopieren"}</button></div></div>
          <div style={{padding:"0 16px 14px"}}><div style={{display:"flex",gap:6}}>{["WhatsApp","SMS","E-Mail","Mehr"].map((ch,i)=>(<button key={i} style={{flex:1,padding:"10px 0",borderRadius:10,border:"none",background:C.soft,color:C.sub,fontSize:10,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>{ch}</button>))}</div></div>
        </Cd></div>
        <div style={{display:"flex",borderBottom:`1px solid ${C.border}`,padding:`0 ${P}px`}}>{[{id:"milestones",l:"Meilensteine"},{id:"friends",l:`Freunde (${friends.length})`}].map(t=>(<button key={t.id} onClick={()=>setTab(t.id)} style={{flex:1,padding:"10px 0",background:"none",border:"none",borderBottom:tab===t.id?`2px solid ${C.purple}`:"2px solid transparent",fontSize:12,fontWeight:700,color:tab===t.id?C.text:C.muted,cursor:"pointer",fontFamily:"inherit"}}>{t.l}</button>))}</div>
        <div style={{padding:`14px ${P}px`}}>
          {tab==="milestones"&&(<div style={{position:"relative",paddingLeft:16}}><div style={{position:"absolute",left:6,top:0,bottom:0,width:2,background:C.soft,borderRadius:1}}/><div style={{position:"absolute",left:6,top:0,width:2,borderRadius:1,background:C.purple,height:"25%"}}/>
            {rws.map((rw,i)=>{const ok=rw.done,isN=!ok&&(i===0||rws[i-1].done); return (<div key={i} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 0",position:"relative"}}><div style={{position:"absolute",left:-12,width:14,height:14,borderRadius:7,background:ok?C.purple:isN?C.card:C.soft,border:ok?"none":`2px solid ${isN?C.purple:C.border}`,display:"flex",alignItems:"center",justifyContent:"center",zIndex:1}}>{ok&&<Check size={8} color="#fff" strokeWidth={3}/>}{isN&&<div style={{width:5,height:5,borderRadius:3,background:C.purple}}/>}</div><Cd style={{flex:1,padding:12}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><div><div style={{fontSize:13,fontWeight:700,color:C.text}}>{rw.count} {rw.count===1?"Freund":"Freunde"}</div><div style={{fontSize:11,color:C.muted,marginTop:1}}>{rw.reward}</div></div>{ok&&<Check size={16} color={C.purple}/>}{isN&&<span style={{fontSize:11,fontWeight:700,color:C.purple}}>Nächstes</span>}{!ok&&!isN&&<Lock size={13} color={C.light}/>}</div></Cd></div>);})}
          </div>)}
          {tab==="friends"&&(<>{friends.map((r,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:11,padding:"12px 0",borderBottom:i<friends.length-1?`1px solid ${C.border}`:"none"}}><div style={{width:36,height:36,borderRadius:11,background:r.status==="joined"?`${C.purple}08`:C.soft,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><span style={{fontSize:13,fontWeight:900,color:r.status==="joined"?C.purple:C.muted}}>{r.name[0]}</span></div><div style={{flex:1}}><div style={{fontSize:13,fontWeight:700,color:C.text}}>{r.name}</div><div style={{fontSize:11,color:C.muted}}>{r.status==="joined"?`+${r.pts} pts`:"Ausstehend"}</div></div>{r.status==="joined"?<Check size={16} color={C.purple}/>:<span style={{fontSize:10,fontWeight:700,color:C.gold,background:`${C.gold}10`,padding:"3px 8px",borderRadius:5}}>Pending</span>}</div>))}<div style={{marginTop:16}}><Btn full icon={Send} onClick={copy}>Weitere einladen</Btn></div></>)}
        </div>
      </div>
    </div>
  );
}

function Home({points,go,onNotif,unreadCount}){
  const lvl=LEVELS.reduce((a,l)=>points>=l.min?l:a,LEVELS[0]);const next=LEVELS[LEVELS.indexOf(lvl)+1];const pct=next?(points-lvl.min)/(next.min-lvl.min):1;const hr=new Date().getHours();const greet=hr<12?"Guten Morgen":hr<18?"Guten Tag":"Guten Abend";
  const chlg=[{title:"Try a new category",reward:150,p:0,t:1,icon:Globe,color:"#2D7D6B"},{title:"Write 3 reviews",reward:300,p:1,t:3,icon:Star,color:C.purple},{title:"Refer a friend",reward:400,p:0,t:2,icon:UserPlus,color:"#C4702B"}];
  const feed=[{title:"Lena M. hat gepostet",sub:"Self-Care Ritual",time:"2h",icon:Camera,go:"creators"},{title:"Wellness Workshop",sub:"Apr 12 · Virtual",time:"5d",icon:Calendar,go:"events"},{title:"Trending",sub:"Nervous about ordering? · 89 likes",time:"1d",icon:Flame,go:"community"},{title:"Max & Nora",sub:"Mystery Box Challenge!",time:"1d",icon:Camera,go:"creators"}];
  return (
    <div style={{paddingBottom:80,position:"relative"}}><Bg v="home"/>
      <div style={{position:"relative",zIndex:1}}>
        <div style={{padding:`36px ${P}px 0`,display:"flex",alignItems:"center",justifyContent:"space-between"}}><div><p style={{fontSize:12,color:C.muted,fontWeight:600,margin:0}}>{greet}</p><h1 style={{fontSize:22,fontWeight:900,color:C.text,margin:"2px 0 0"}}>Circle</h1></div>
          <div style={{display:"flex",alignItems:"center",gap:10}}><button onClick={onNotif} style={{width:36,height:36,borderRadius:12,background:C.soft,border:"none",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",position:"relative"}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke={C.sub} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>{unreadCount>0&&<div style={{position:"absolute",top:-2,right:-2,minWidth:16,height:16,borderRadius:8,background:C.purple,display:"flex",alignItems:"center",justifyContent:"center",border:"2px solid #fff"}}><span style={{fontSize:8,fontWeight:900,color:"#fff"}}>{unreadCount}</span></div>}</button>
            <div onClick={()=>go("profile")} style={{cursor:"pointer"}}><Ring size={56} sw={4} pct={pct}><span style={{fontSize:13,fontWeight:900,color:C.text}}>{points}</span></Ring></div></div></div>
        {next&&<p style={{fontSize:12,color:C.muted,fontWeight:600,padding:`3px ${P}px 0`,margin:0}}>{next.min-points} bis <span style={{fontWeight:700,color:C.text}}>{next.name}</span></p>}
        <div style={{padding:`20px ${P}px 0`}}><div onClick={()=>go("earn")} style={{padding:"18px 20px",borderRadius:16,background:C.text,cursor:"pointer",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:-35,right:-25,width:120,height:120,borderRadius:60,background:C.purple,opacity:.25}}/><div style={{position:"relative",zIndex:1}}><div style={{display:"flex",alignItems:"center",gap:5,marginBottom:6}}><Zap size={13} color="#d8ffab" strokeWidth={2.5}/><span style={{fontSize:9,fontWeight:800,color:"#d8ffab",textTransform:"uppercase",letterSpacing:".06em"}}>Nächster Schritt</span></div><h2 style={{fontSize:15,fontWeight:800,color:"#fff",margin:"0 0 3px"}}>Review schreiben & Punkte sammeln</h2><p style={{fontSize:11,color:"rgba(255,255,255,.4)",margin:0}}>+50 Punkte</p></div></div></div>
        <div style={{padding:"24px 0 0"}}><h2 style={{fontSize:12,fontWeight:800,textTransform:"uppercase",letterSpacing:".03em",color:C.muted,padding:`0 ${P}px`,margin:"0 0 10px"}}>Challenges</h2>
          <div style={{display:"flex",gap:10,overflowX:"auto",padding:`0 ${P}px 4px`}}>{chlg.map((c,i)=>{const cp=c.t>0?c.p/c.t:0; return (<Cd key={i} style={{minWidth:180,padding:14,flexShrink:0}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:12}}><div style={{width:36,height:36,borderRadius:11,background:`${c.color}0a`,display:"flex",alignItems:"center",justifyContent:"center"}}><c.icon size={16} color={c.color} strokeWidth={1.8}/></div><Ring size={38} sw={3} pct={cp} color={c.color}><span style={{fontSize:10,fontWeight:800,color:C.text}}>{c.p}/{c.t}</span></Ring></div><h3 style={{fontSize:13,fontWeight:700,color:C.text,margin:"0 0 2px"}}>{c.title}</h3><span style={{fontSize:11,fontWeight:700,color:c.color}}>+{c.reward} pts</span></Cd>);})}</div></div>
        <div style={{padding:`24px ${P}px 16px`}}><h2 style={{fontSize:12,fontWeight:800,textTransform:"uppercase",letterSpacing:".03em",color:C.muted,margin:"0 0 10px"}}>Was ist neu</h2>
          {feed.map((f,i)=>{const FI=f.icon; return (<div key={i} onClick={()=>go(f.go)} style={{display:"flex",gap:10,padding:"12px 0",borderBottom:i<feed.length-1?`1px solid ${C.border}`:"none",cursor:"pointer"}}><div style={{width:34,height:34,borderRadius:10,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><FI size={14} color={C.sub} strokeWidth={1.8}/></div><div style={{flex:1,minWidth:0}}><div style={{fontSize:12,fontWeight:700,color:C.text}}>{f.title}</div><div style={{fontSize:11,color:C.muted,marginTop:1,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{f.sub}</div></div><span style={{fontSize:10,color:C.light,flexShrink:0}}>{f.time}</span></div>);})}</div>
      </div>
    </div>
  );
}

function Earn({points,addPoints}){
  const[sel,setSel]=useState(null);const[review,setReview]=useState("");const[rating,setRating]=useState(0);const[anim,setAnim]=useState({show:false,amt:0});const[done,setDone]=useState({});const[filter,setFilter]=useState("All");const[success,setSuccess]=useState(false);const[detail,setDetail]=useState(null);
  const cats=["All",...new Set(PRODUCTS.map(p=>p.cat))];const sorted=[...PRODUCTS].sort((a,b)=>(done[`r${a.id}`]?1:0)-(done[`r${b.id}`]?1:0));const list=filter==="All"?sorted:sorted.filter(p=>p.cat===filter);const reviewed=Object.keys(done).filter(k=>k.startsWith("r")).length;const hero=list.find(p=>!done[`r${p.id}`])||list[0];const rest=list.filter(p=>p.id!==hero?.id);
  const submit=()=>{if(!sel||rating===0)return;const pts=review.length>50?75:50;setSuccess(true);setTimeout(()=>{setSuccess(false);setAnim({show:true,amt:pts});addPoints(pts);setDone(p=>({...p,[`r${sel.id}`]:true}));setReview("");setRating(0);setSel(null)},1600)};
  const share=(p,e)=>{e?.stopPropagation();if(done[`s${p.id}`])return;setAnim({show:true,amt:30});addPoints(30);setDone(prev=>({...prev,[`s${p.id}`]:true}))};

  if(success) return (<div style={{position:"fixed",inset:0,display:"flex",alignItems:"center",justifyContent:"center",background:C.bg,zIndex:400,animation:"fi .2s"}}><div style={{animation:"pop .35s cubic-bezier(.34,1.56,.64,1)",textAlign:"center"}}><div style={{width:72,height:72,borderRadius:36,background:`${C.purple}10`,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px"}}><Check size={32} color={C.purple} strokeWidth={2.5}/></div><h2 style={{fontSize:20,fontWeight:900,color:C.text,margin:"0 0 4px"}}>Danke!</h2><p style={{fontSize:13,color:C.muted}}>+{review.length>50?75:50} Punkte</p></div></div>);
  if(detail&&!sel) return (<ProductDetail product={detail} onBack={()=>setDetail(null)} onReview={()=>{setSel(detail);setDetail(null)}}/>);
  if(sel) return (
    <div style={{paddingBottom:80}}><Anim show={anim.show} amount={anim.amt} onDone={()=>setAnim({show:false,amt:0})}/>
      <div style={{padding:`18px ${P}px`}}><button onClick={()=>{setSel(null);setRating(0);setReview("")}} style={{background:"none",border:"none",cursor:"pointer",display:"flex",alignItems:"center",gap:5,fontSize:12,fontWeight:600,color:C.muted,padding:0,fontFamily:"inherit",marginBottom:20}}><ArrowLeft size={15}/> Zurück</button>
        <div style={{height:180,borderRadius:16,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center",marginBottom:20}}><Package size={44} color={C.muted} strokeWidth={1}/></div>
        <div style={{fontSize:10,fontWeight:700,color:C.purple,textTransform:"uppercase",letterSpacing:".06em",marginBottom:3}}>{sel.cat}</div><h2 style={{fontSize:20,fontWeight:900,color:C.text,margin:"0 0 2px"}}>{sel.name}</h2><p style={{fontSize:14,fontWeight:700,color:C.text,margin:"0 0 24px"}}>€{sel.price}</p>
        <div style={{fontSize:11,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:".04em",marginBottom:8}}>Bewertung</div>
        <div style={{display:"flex",gap:6,marginBottom:20}}>{[1,2,3,4,5].map(s=>(<button key={s} onClick={()=>setRating(s)} style={{flex:1,height:44,borderRadius:12,border:"none",cursor:"pointer",background:s<=rating?`${C.gold}15`:C.soft,display:"flex",alignItems:"center",justifyContent:"center"}}><Star size={20} color={s<=rating?C.gold:C.light} fill={s<=rating?C.gold:"none"} strokeWidth={1.5}/></button>))}</div>
        <div style={{fontSize:11,fontWeight:700,color:C.muted,textTransform:"uppercase",letterSpacing:".04em",marginBottom:8}}>Feedback</div>
        <textarea value={review} onChange={e=>setReview(e.target.value)} placeholder="Was hat dir gefallen?" style={{width:"100%",minHeight:100,padding:14,borderRadius:14,background:C.soft,border:"none",color:C.text,fontSize:13,lineHeight:1.6,resize:"none",outline:"none",fontFamily:"inherit",boxSizing:"border-box"}}/>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",margin:"5px 0 20px"}}><span style={{fontSize:11,color:C.muted}}>{review.length} Zeichen</span>{review.length>=50&&<span style={{fontSize:11,fontWeight:700,color:C.purple}}>Bonus! +75</span>}</div>
        <Btn full disabled={rating===0} onClick={submit} icon={Send}>Absenden</Btn>
      </div>
    </div>
  );
  return (
    <div style={{paddingBottom:80,position:"relative"}}><Bg v="earn"/><Anim show={anim.show} amount={anim.amt} onDone={()=>setAnim({show:false,amt:0})}/>
      <div style={{position:"relative",zIndex:1}}>
        <div style={{padding:`28px ${P}px 0`,display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:12}}><h1 style={{fontSize:22,fontWeight:900,color:C.text,margin:0}}>Earn</h1><div style={{display:"flex",alignItems:"center",gap:8}}><Ring size={36} sw={3} pct={reviewed/PRODUCTS.length}><span style={{fontSize:10,fontWeight:900,color:C.text}}>{reviewed}/{PRODUCTS.length}</span></Ring><span style={{fontSize:13,fontWeight:800,color:C.purple}}>{points} pts</span></div></div>
        <div style={{display:"flex",gap:6,padding:`0 ${P}px 14px`,overflowX:"auto"}}>{cats.map(c=>(<Pill key={c} active={filter===c} onClick={()=>setFilter(c)}>{c}</Pill>))}</div>
        {hero&&<div style={{padding:`0 ${P}px`}}><div style={{borderRadius:16,overflow:"hidden",background:C.card,boxShadow:C.sh,opacity:done[`r${hero.id}`]?.35:1}}><div onClick={()=>!done[`r${hero.id}`]&&setDetail(hero)} style={{height:240,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center",cursor:done[`r${hero.id}`]?"default":"pointer",position:"relative"}}><Package size={44} color={C.muted} strokeWidth={1}/>{!done[`r${hero.id}`]&&<span style={{position:"absolute",top:12,left:12,fontSize:9,fontWeight:800,color:C.purple,background:`${C.purple}0a`,padding:"3px 10px",borderRadius:7}}>Empfohlen</span>}</div>
          <div style={{padding:"14px 16px 16px"}}><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:"uppercase",marginBottom:2}}>{hero.cat}</div><div style={{display:"flex",alignItems:"baseline",justifyContent:"space-between",marginBottom:12}}><h3 style={{fontSize:16,fontWeight:800,color:C.text,margin:0}}>{hero.name}</h3><span style={{fontSize:15,fontWeight:800,color:C.text}}>€{hero.price}</span></div>
            <div style={{display:"flex",gap:8}}><button onClick={()=>!done[`r${hero.id}`]&&setSel(hero)} disabled={done[`r${hero.id}`]} style={{flex:1,padding:"11px 0",borderRadius:12,border:"none",background:done[`r${hero.id}`]?C.soft:C.text,color:done[`r${hero.id}`]?C.muted:"#fff",fontSize:13,fontWeight:700,cursor:done[`r${hero.id}`]?"default":"pointer",fontFamily:"inherit",display:"flex",alignItems:"center",justifyContent:"center",gap:5}}><Star size={14} strokeWidth={2}/> Review · +50</button><button onClick={e=>share(hero,e)} disabled={done[`s${hero.id}`]} style={{padding:"11px 16px",borderRadius:12,border:`1.5px solid ${done[`s${hero.id}`]?C.border:C.text}`,background:"transparent",cursor:done[`s${hero.id}`]?"default":"pointer",fontFamily:"inherit"}}>{done[`s${hero.id}`]?<Check size={14} color={C.muted}/>:<Share2 size={14} color={C.text}/>}</button></div></div></div></div>}
        <div style={{padding:`14px ${P}px 0`}}>{rest.map((p,i)=>{const rd=done[`r${p.id}`],sd=done[`s${p.id}`]; return (<div key={p.id} onClick={()=>{if(!rd)setDetail(p)}} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 0",borderBottom:i<rest.length-1?`1px solid ${C.border}`:"none",cursor:rd?"default":"pointer",opacity:rd?.3:1}}><div style={{width:50,height:50,borderRadius:12,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><Package size={20} color={C.muted} strokeWidth={1.3}/></div><div style={{flex:1,minWidth:0}}><div style={{fontSize:9,fontWeight:700,color:C.muted,textTransform:"uppercase",marginBottom:1}}>{p.cat}</div><div style={{fontSize:13,fontWeight:700,color:C.text}}>{p.name}</div><div style={{fontSize:12,fontWeight:600,color:C.sub}}>€{p.price}</div></div><div style={{display:"flex",gap:5,flexShrink:0}}><button onClick={e=>{e.stopPropagation();if(!rd)setSel(p)}} disabled={rd} style={{padding:"7px 11px",borderRadius:8,border:"none",background:rd?C.soft:C.text,color:rd?C.muted:"#fff",fontSize:10,fontWeight:700,cursor:rd?"default":"pointer",fontFamily:"inherit"}}>+50</button><button onClick={e=>{e.stopPropagation();share(p,e)}} disabled={sd} style={{padding:"7px 9px",borderRadius:8,border:`1.5px solid ${sd?C.border:C.text}`,background:"transparent",cursor:sd?"default":"pointer",fontFamily:"inherit"}}>{sd?<Check size={11} color={C.muted}/>:<Share2 size={11} color={C.text}/>}</button></div></div>);})}</div>
      </div>
    </div>
  );
}

function Couple(){
  const[started,setStarted]=useState(false);const[list,setList]=useState([]);const[matchAnim,setMatchAnim]=useState(null);const[filter,setFilter]=useState("All");
  const partner=[2,4,6,7];const cats=["All",...new Set(PRODUCTS.map(p=>p.cat))];const filtered=filter==="All"?PRODUCTS:PRODUCTS.filter(p=>p.cat===filter);const isMatch=id=>partner.includes(id);const matches=list.filter(w=>isMatch(w.id));
  const add=p=>{if(list.find(w=>w.id===p.id))return;setList(prev=>[...prev,p]);if(isMatch(p.id)){setMatchAnim(p);setTimeout(()=>setMatchAnim(null),1800)}};

  if(matchAnim) return (<div style={{position:"fixed",inset:0,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(250,250,248,.95)",backdropFilter:"blur(16px)",zIndex:400,animation:"fi .15s"}}><div style={{animation:"pop .35s cubic-bezier(.34,1.56,.64,1)",textAlign:"center"}}><div style={{width:72,height:72,borderRadius:36,background:`${C.coral}10`,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px"}}><Heart size={32} color={C.coral} fill={C.coral}/></div><h2 style={{fontSize:20,fontWeight:900,color:C.text,margin:"0 0 4px"}}>It's a Match!</h2><p style={{fontSize:13,color:C.muted}}>Ihr wollt beide <span style={{fontWeight:700,color:C.purple}}>{matchAnim.name}</span></p></div></div>);
  if(!started) return (
    <div style={{display:"flex",flexDirection:"column",minHeight:"100vh",paddingBottom:80}}><Bg v="couple"/>
      <div style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"0 36px",position:"relative",zIndex:1}}>
        <div style={{width:80,height:80,borderRadius:40,background:`${C.coral}08`,display:"flex",alignItems:"center",justifyContent:"center",marginBottom:24}}><Heart size={34} color={C.coral} strokeWidth={1.4}/></div>
        <h1 style={{fontSize:22,fontWeight:900,color:C.text,textAlign:"center",margin:"0 0 10px",lineHeight:1.3}}>Wählt getrennt,<br/>entdeckt gemeinsam</h1>
        <p style={{fontSize:13,color:C.sub,textAlign:"center",lineHeight:1.6,margin:"0 0 28px"}}>Gleiche Produkte gewählt? Match!</p>
        <Btn full onClick={()=>setStarted(true)} icon={Heart}>Let's go</Btn>
        <Cd style={{marginTop:18,display:"flex",alignItems:"center",gap:10,width:"100%"}}><div style={{width:30,height:30,borderRadius:9,background:C.purple,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:11,fontWeight:900,color:"#fff"}}>A</span></div><div style={{flex:1}}><div style={{fontSize:12,fontWeight:700,color:C.text}}>Alex ist verbunden</div></div><Check size={14} color={C.purple}/></Cd>
      </div>
    </div>
  );
  return (
    <div style={{display:"flex",flexDirection:"column",height:"100vh",paddingBottom:80}}><Bg v="couple"/>
      <div style={{position:"relative",zIndex:1,padding:`24px ${P}px 0`}}><h1 style={{fontSize:22,fontWeight:900,color:C.text,margin:"0 0 14px"}}>Couple</h1>
        <div style={{display:"flex",gap:8,marginBottom:14}}>{[{l:"Picks",v:list.length},{l:"Matches",v:matches.length,hl:matches.length>0},{l:"Übrig",v:PRODUCTS.length-list.length}].map((s,i)=>(<div key={i} style={{flex:1,padding:"10px 6px",borderRadius:12,background:s.hl?`${C.coral}08`:C.card,boxShadow:C.sh,textAlign:"center"}}><div style={{fontSize:16,fontWeight:900,color:s.hl?C.coral:C.text}}>{s.v}</div><div style={{fontSize:9,fontWeight:700,color:C.muted}}>{s.l}</div></div>))}</div></div>
      {matches.length>0&&<div style={{padding:`0 ${P}px 12px`,position:"relative",zIndex:1}}><div style={{display:"flex",gap:8,overflowX:"auto"}}>{matches.map(p=>(<Cd key={p.id} style={{minWidth:140,padding:12,flexShrink:0,border:`1px solid ${C.coral}12`}}><div style={{display:"flex",alignItems:"center",gap:4,marginBottom:6}}><Heart size={10} color={C.coral} fill={C.coral}/><span style={{fontSize:9,fontWeight:800,color:C.coral}}>MATCH</span></div><div style={{fontSize:12,fontWeight:700,color:C.text,marginBottom:1}}>{p.name}</div><div style={{fontSize:11,color:C.muted}}>€{p.price}</div><button style={{marginTop:8,width:"100%",padding:"7px 0",borderRadius:8,border:"none",background:C.text,color:"#fff",fontSize:10,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>Shop</button></Cd>))}</div></div>}
      <div style={{display:"flex",gap:6,padding:`0 ${P}px 8px`,overflowX:"auto",position:"relative",zIndex:1}}>{cats.map(c=>(<Pill key={c} active={filter===c} onClick={()=>setFilter(c)}>{c}</Pill>))}</div>
      <div style={{flex:1,overflowY:"auto",padding:`0 ${P}px`,position:"relative",zIndex:1}}>{filtered.map((p,i)=>{const added=list.find(w=>w.id===p.id),matched=added&&isMatch(p.id); return (<div key={p.id} style={{display:"flex",alignItems:"center",gap:11,padding:"11px 0",borderBottom:i<filtered.length-1?`1px solid ${C.border}`:"none",opacity:added?.45:1}}><div style={{width:44,height:44,borderRadius:12,background:matched?`${C.coral}08`:C.soft,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{matched?<Heart size={16} color={C.coral} fill={C.coral}/>:<Package size={16} color={C.muted} strokeWidth={1.4}/>}</div><div style={{flex:1,minWidth:0}}><div style={{fontSize:13,fontWeight:700,color:C.text}}>{p.name}</div><div style={{fontSize:11,color:C.muted}}>€{p.price}</div></div>{added?<div style={{display:"flex",alignItems:"center",gap:5}}>{matched&&<span style={{fontSize:9,fontWeight:800,color:C.coral,background:`${C.coral}0a`,padding:"2px 7px",borderRadius:5}}>MATCH</span>}<button onClick={()=>setList(prev=>prev.filter(w=>w.id!==p.id))} style={{background:"none",border:"none",cursor:"pointer",padding:2}}><X size={13} color={C.light}/></button></div>:<button onClick={()=>add(p)} style={{width:34,height:34,borderRadius:10,border:"none",background:C.text,color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><Plus size={15} strokeWidth={2.5}/></button>}</div>);})}</div>
    </div>
  );
}

function Community(){
  const[topic,setTopic]=useState("All");const[modal,setModal]=useState(null);const[searchQ,setSearchQ]=useState("");const[postTitle,setPostTitle]=useState("");const[postBody,setPostBody]=useState("");const[liked,setLiked]=useState({});
  const tpcs=[{id:"All",i:Sparkles},{id:"Beginners",i:Heart},{id:"Couples",i:UserPlus},{id:"Wellness",i:Zap},{id:"Products",i:Package},{id:"Tips",i:Star}];
  const filtered=topic==="All"?DISCUSSIONS:DISCUSSIONS.filter(d=>d.topic===topic);const hot=DISCUSSIONS.filter(d=>d.hot).sort((a,b)=>b.likes-a.likes).slice(0,3);const searched=searchQ.trim()?DISCUSSIONS.filter(d=>d.title.toLowerCase().includes(searchQ.toLowerCase())):[];const av=["M","S","L","A","K","T","J"];

  return (
    <div style={{display:"flex",flexDirection:"column",height:"100vh"}}><Bg v="community"/>
      <div style={{position:"relative",zIndex:1,padding:`24px ${P}px 0`}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:12}}><h1 style={{fontSize:22,fontWeight:900,color:C.text,margin:0}}>Community</h1><button onClick={()=>setModal("search")} style={{width:34,height:34,borderRadius:10,background:C.soft,border:"none",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><Search size={15} color={C.sub}/></button></div>
        <div style={{display:"flex",gap:8,marginBottom:14}}>{[{l:"Mitglieder",v:"2.4K"},{l:"Diskussionen",v:"847"},{l:"Deine Posts",v:"2"}].map((s,i)=>(<div key={i} style={{flex:1,padding:"10px 6px",borderRadius:12,background:C.card,boxShadow:C.sh,textAlign:"center"}}><div style={{fontSize:16,fontWeight:900,color:C.text}}>{s.v}</div><div style={{fontSize:9,fontWeight:700,color:C.muted}}>{s.l}</div></div>))}</div></div>
      <div style={{display:"flex",gap:6,padding:`0 ${P}px 10px`,overflowX:"auto",position:"relative",zIndex:1}}>{tpcs.map(t=>(<button key={t.id} onClick={()=>setTopic(t.id)} style={{padding:"6px 12px",borderRadius:20,border:`1.5px solid ${topic===t.id?C.purple:C.border}`,background:topic===t.id?C.purple:C.bg,color:topic===t.id?"#fff":C.sub,fontSize:10,fontWeight:700,cursor:"pointer",display:"flex",alignItems:"center",gap:4,whiteSpace:"nowrap",fontFamily:"inherit"}}><t.i size={11} strokeWidth={2}/> {t.id}</button>))}</div>
      <div style={{flex:1,overflowY:"auto",padding:`0 ${P}px 96px`,position:"relative",zIndex:1}}>
        {topic==="All"&&<div style={{marginBottom:16}}><div style={{fontSize:11,fontWeight:800,textTransform:"uppercase",letterSpacing:".03em",color:C.muted,marginBottom:8}}>Trending</div><div style={{display:"flex",gap:10,overflowX:"auto",paddingBottom:4}}>{hot.map(d=>(<Cd key={d.id} style={{minWidth:200,padding:14,flexShrink:0,borderLeft:`3px solid ${tc(d.topic)}`}}><div style={{display:"flex",alignItems:"center",gap:5,marginBottom:6}}><span style={{fontSize:9,fontWeight:800,color:"#fff",background:tc(d.topic),padding:"2px 7px",borderRadius:5}}>{d.topic}</span><Flame size={10} color={C.coral}/></div><h3 style={{fontSize:12,fontWeight:700,color:C.text,margin:"0 0 8px",lineHeight:1.4}}>{d.title}</h3><div style={{display:"flex",gap:8,fontSize:10,color:C.muted}}><span style={{display:"flex",alignItems:"center",gap:3}}><Heart size={10}/> {d.likes}</span><span style={{display:"flex",alignItems:"center",gap:3}}><MessageCircle size={10}/> {d.replies}</span></div></Cd>))}</div></div>}
        {filtered.map((d,i)=>{const il=liked[d.id]; return (<Cd key={d.id} style={{marginBottom:10,padding:14}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><div style={{width:28,height:28,borderRadius:8,background:tc(d.topic),display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><span style={{fontSize:11,fontWeight:900,color:"#fff"}}>{av[i%7]}</span></div><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:4}}><span style={{fontSize:9,fontWeight:800,color:"#fff",background:tc(d.topic),padding:"2px 6px",borderRadius:4}}>{d.topic}</span>{d.hot&&<Flame size={9} color={C.coral}/>}</div><span style={{fontSize:10,color:C.light}}>{d.time}</span></div></div><h3 style={{fontSize:13,fontWeight:700,color:C.text,margin:"0 0 8px",lineHeight:1.4}}>{d.title}</h3><div style={{display:"flex",alignItems:"center",gap:3}}><button onClick={()=>setLiked(p=>({...p,[d.id]:!p[d.id]}))} style={{background:"none",border:"none",cursor:"pointer",display:"flex",alignItems:"center",gap:3,fontSize:11,fontWeight:600,color:il?C.coral:C.muted,padding:"3px 8px 3px 0"}}><Heart size={14} fill={il?C.coral:"none"} color={il?C.coral:C.muted} strokeWidth={1.8}/> {d.likes+(il?1:0)}</button><span style={{display:"flex",alignItems:"center",gap:3,fontSize:11,color:C.muted,padding:"3px 8px"}}><MessageCircle size={13} strokeWidth={1.8}/> {d.replies}</span></div></Cd>);})}
      </div>
      <button onClick={()=>setModal("post")} style={{position:"fixed",bottom:76,right:"50%",transform:"translateX(calc(50% + 165px))",width:46,height:46,borderRadius:14,background:C.text,border:"none",boxShadow:"0 4px 14px rgba(0,0,0,.1)",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",zIndex:10}}><Plus size={18} color="#fff" strokeWidth={2.5}/></button>
      {modal&&(<div style={{position:"fixed",inset:0,zIndex:200,background:C.bg,display:"flex",flexDirection:"column",animation:"fi .15s"}}><div style={{padding:`18px ${P}px 0`,display:"flex",alignItems:"center",justifyContent:"space-between"}}><h2 style={{fontSize:18,fontWeight:900,color:C.text,margin:0}}>{modal==="search"?"Suchen":"Neues Thema"}</h2><button onClick={()=>{setModal(null);setSearchQ("")}} style={{background:"none",border:"none",cursor:"pointer"}}><X size={18} color={C.sub}/></button></div>
        {modal==="search"&&(<div style={{padding:P,flex:1,overflowY:"auto"}}><div style={{display:"flex",alignItems:"center",gap:8,padding:"10px 14px",borderRadius:12,background:C.soft,marginBottom:16}}><Search size={15} color={C.muted}/><input autoFocus value={searchQ} onChange={e=>setSearchQ(e.target.value)} placeholder="Suchen..." style={{flex:1,border:"none",background:"none",outline:"none",fontSize:13,color:C.text,fontFamily:"inherit"}}/></div>{searchQ.trim()?(searched.length>0?searched.map(d=>(<Cd key={d.id} style={{marginBottom:8,padding:12}}><span style={{fontSize:9,fontWeight:800,color:"#fff",background:tc(d.topic),padding:"2px 6px",borderRadius:4}}>{d.topic}</span><h3 style={{fontSize:12,fontWeight:700,color:C.text,margin:"5px 0 0"}}>{d.title}</h3></Cd>)):<p style={{textAlign:"center",color:C.muted,padding:28}}>Keine Ergebnisse</p>):<p style={{textAlign:"center",color:C.light,padding:36}}>Suche nach Themen</p>}</div>)}
        {modal==="post"&&(<div style={{padding:P,flex:1,overflowY:"auto"}}><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:"uppercase",margin:"12px 0 6px"}}>Titel</div><input value={postTitle} onChange={e=>setPostTitle(e.target.value)} placeholder="Was beschäftigt dich?" style={{width:"100%",padding:"12px 14px",borderRadius:12,background:C.soft,border:"none",color:C.text,fontSize:14,fontWeight:600,outline:"none",fontFamily:"inherit",boxSizing:"border-box",marginBottom:16}}/><div style={{fontSize:10,fontWeight:700,color:C.muted,textTransform:"uppercase",margin:"0 0 6px"}}>Details</div><textarea value={postBody} onChange={e=>setPostBody(e.target.value)} placeholder="Mehr Kontext..." style={{width:"100%",minHeight:100,padding:14,borderRadius:14,background:C.soft,border:"none",color:C.text,fontSize:13,lineHeight:1.6,resize:"none",outline:"none",fontFamily:"inherit",boxSizing:"border-box",marginBottom:14}}/><Btn full disabled={!postTitle.trim()} onClick={()=>{setModal(null);setPostTitle("");setPostBody("")}} icon={Send}>Veröffentlichen</Btn></div>)}
      </div>)}
    </div>
  );
}

function CreatorsScreen(){
  const[sel,setSel]=useState(null);const[copied,setCopied]=useState(null);const[tab,setTab]=useState("content");const[liked,setLiked]=useState({});const[following,setFollowing]=useState({1:true,2:true});const[feedFilter,setFeedFilter]=useState("All");
  const cp=(code,e)=>{e?.stopPropagation();setCopied(code);setTimeout(()=>setCopied(null),2000)};const tl=(k,e)=>{e.stopPropagation();setLiked(p=>({...p,[k]:!p[k]}))};const tf=(id,e)=>{e?.stopPropagation();setFollowing(p=>({...p,[id]:!p[id]}))};
  const types=["All","Tutorial","Review","Unboxing","Vlog","Q&A"];const hasNew=cr=>cr.content.some(c=>c.time==="1d"||c.time==="2d"||c.time==="3d");
  const allContent=CREATORS.flatMap(cr=>cr.content.map(c=>({...c,creator:cr}))).sort((a,b)=>{const o={"1d":1,"2d":2,"3d":3,"4d":4,"5d":5,"1w":7,"2w":14};return (o[a.time]||99)-(o[b.time]||99)});const feedList=feedFilter==="All"?allContent:allContent.filter(c=>c.type===feedFilter);
  const cmts={"1-0":{u:"Lisa",t:"Routine hat mich verändert!"},"2-0":{u:"Marie",t:"Genau so machen wir es!"},"4-0":{u:"Nils",t:"Chaos war zu gut 😂"}};

  if(sel){const picks=PRODUCTS.filter(p=>sel.picks.includes(p.id)); return (
    <div style={{paddingBottom:80,position:"relative"}}><Bg v="creators"/><div style={{position:"relative",zIndex:1}}>
      <div style={{padding:`14px ${P}px 0`}}><button onClick={()=>{setSel(null);setTab("content")}} style={{background:"none",border:"none",cursor:"pointer",display:"flex",alignItems:"center",gap:5,fontSize:12,fontWeight:600,color:C.muted,padding:0,fontFamily:"inherit"}}><ArrowLeft size={15}/> Zurück</button></div>
      <div style={{padding:`18px ${P}px 0`,display:"flex",alignItems:"center",gap:14}}><div style={{width:64,height:64,borderRadius:22,background:C.purple,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><span style={{fontSize:20,fontWeight:900,color:"#fff"}}>{ini(sel.name)}</span></div><div style={{flex:1}}><h2 style={{fontSize:18,fontWeight:900,color:C.text,margin:0}}>{sel.name}</h2><p style={{fontSize:12,color:C.purple,fontWeight:600,margin:"1px 0"}}>{sel.handle}</p><span style={{fontSize:13,fontWeight:800,color:C.text}}>{sel.followers} <span style={{fontSize:10,color:C.muted}}>Followers</span></span></div></div>
      <div style={{padding:`12px ${P}px 0`,display:"flex",gap:8}}><button onClick={e=>tf(sel.id,e)} style={{flex:1,padding:"10px 0",borderRadius:12,border:following[sel.id]?`1.5px solid ${C.border}`:"none",background:following[sel.id]?"transparent":C.purple,color:following[sel.id]?C.sub:"#fff",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>{following[sel.id]?"Following":"Follow"}</button><button onClick={e=>cp(sel.code,e)} style={{flex:1,padding:"10px 0",borderRadius:12,border:"none",background:C.text,color:"#fff",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>{copied===sel.code?"Copied!":sel.code+" · "+sel.discount}</button></div>
      <p style={{fontSize:12,color:C.sub,padding:`10px ${P}px 0`,lineHeight:1.5,margin:0}}>{sel.bio}</p>
      <div style={{display:"flex",borderBottom:`1px solid ${C.border}`,padding:`12px ${P}px 0`}}>{["content","picks"].map(t=>(<button key={t} onClick={()=>setTab(t)} style={{flex:1,padding:"10px 0",background:"none",border:"none",borderBottom:tab===t?`2px solid ${C.purple}`:"2px solid transparent",fontSize:12,fontWeight:700,color:tab===t?C.text:C.muted,cursor:"pointer",fontFamily:"inherit"}}>{t==="content"?"Content":"Picks"} ({t==="content"?sel.content.length:picks.length})</button>))}</div>
      <div style={{padding:`14px ${P}px`}}>
        {tab==="content"&&sel.content.map((c,i)=>{const k=`${sel.id}-${i}`,prod=c.product?PRODUCTS.find(p=>p.id===c.product):null,il=liked[k],cm=cmts[k]; return (<Cd key={i} style={{marginBottom:10,padding:0,overflow:"hidden"}}><div style={{height:160,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center",position:"relative"}}><Eye size={22} color={C.text}/><div style={{position:"absolute",top:10,left:10,display:"flex",gap:4}}><span style={{fontSize:9,fontWeight:800,color:"#fff",background:tcc(c.type),padding:"3px 8px",borderRadius:6}}>{c.type}</span>{c.exclusive&&<span style={{fontSize:9,fontWeight:800,color:C.purple,background:"rgba(255,255,255,.9)",padding:"3px 8px",borderRadius:6}}>Exklusiv</span>}</div></div>
          <div style={{padding:"12px 14px"}}><h4 style={{fontSize:14,fontWeight:800,color:C.text,margin:"0 0 4px"}}>{c.title}</h4><p style={{fontSize:12,color:C.sub,margin:"0 0 10px",lineHeight:1.5}}>{c.desc}</p>
            {prod&&<div style={{display:"flex",alignItems:"center",gap:8,padding:"8px 10px",borderRadius:10,background:C.soft,marginBottom:10}}><Package size={13} color={C.muted}/><div style={{flex:1}}><div style={{fontSize:11,fontWeight:700,color:C.text}}>{prod.name}</div><div style={{display:"flex",gap:4}}><span style={{fontSize:10,color:C.muted,textDecoration:"line-through"}}>€{prod.price}</span><span style={{fontSize:10,fontWeight:800,color:C.purple}}>€{(parseFloat(prod.price)*(1-parseInt(sel.discount)/100)).toFixed(2)}</span></div></div><ShoppingBag size={12} color={C.text}/></div>}
            <div style={{display:"flex",alignItems:"center",gap:3}}><button onClick={e=>tl(k,e)} style={{background:"none",border:"none",cursor:"pointer",display:"flex",alignItems:"center",gap:3,fontSize:11,fontWeight:600,color:il?C.coral:C.muted,padding:"3px 8px 3px 0"}}><Heart size={14} fill={il?C.coral:"none"} color={il?C.coral:C.muted} strokeWidth={1.8}/> {c.likes+(il?1:0)}</button><span style={{display:"flex",alignItems:"center",gap:3,fontSize:11,color:C.muted,padding:"3px 8px"}}><MessageCircle size={13} strokeWidth={1.8}/> {c.comments}</span></div>
            {cm&&<div style={{marginTop:8,padding:"8px 10px",borderRadius:8,background:C.soft,fontSize:11}}><span style={{fontWeight:700,color:C.text}}>{cm.u}</span> <span style={{color:C.sub}}>{cm.t}</span></div>}
          </div></Cd>);})}
        {tab==="picks"&&picks.map((p,i)=>(<div key={p.id} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 0",borderBottom:i<picks.length-1?`1px solid ${C.border}`:"none"}}><div style={{width:48,height:48,borderRadius:12,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><Package size={20} color={C.muted} strokeWidth={1.3}/></div><div style={{flex:1}}><div style={{fontSize:13,fontWeight:700,color:C.text}}>{p.name}</div><div style={{display:"flex",gap:5}}><span style={{fontSize:11,color:C.muted,textDecoration:"line-through"}}>€{p.price}</span><span style={{fontSize:12,fontWeight:800,color:C.purple}}>€{(parseFloat(p.price)*(1-parseInt(sel.discount)/100)).toFixed(2)}</span></div></div><div style={{padding:"8px 12px",borderRadius:8,background:C.text,color:"#fff",fontSize:11,fontWeight:700}}>Shop</div></div>))}
      </div>
    </div></div>
  );}
  return (
    <div style={{paddingBottom:80,position:"relative"}}><Bg v="creators"/><div style={{position:"relative",zIndex:1}}>
      <div style={{padding:`24px ${P}px 16px`}}><h1 style={{fontSize:22,fontWeight:900,color:C.text,margin:"0 0 2px"}}>Creators</h1><p style={{fontSize:12,color:C.muted,margin:0}}>Exklusiver Content</p></div>
      <div style={{padding:`0 ${P}px 14px`}}><div style={{display:"flex",gap:14,overflowX:"auto"}}>{CREATORS.map(cr=>{const nw=hasNew(cr); return (<div key={cr.id} onClick={()=>setSel(cr)} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:6,cursor:"pointer",flexShrink:0}}><div style={{width:56,height:56,borderRadius:18,padding:nw?2:0,background:nw?`linear-gradient(135deg,${C.purple},${C.coral})`:"transparent"}}><div style={{width:nw?52:56,height:nw?52:56,borderRadius:nw?16:18,background:C.purple,display:"flex",alignItems:"center",justifyContent:"center",border:nw?"2px solid #fff":"none"}}><span style={{fontSize:15,fontWeight:900,color:"#fff"}}>{ini(cr.name)}</span></div></div><span style={{fontSize:10,fontWeight:700,color:C.text,maxWidth:60,textAlign:"center",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{cr.name}</span></div>);})}</div></div>
      <div style={{display:"flex",gap:6,padding:`0 ${P}px 14px`,overflowX:"auto"}}>{types.map(t=>(<Pill key={t} active={feedFilter===t} onClick={()=>setFeedFilter(t)}>{t}</Pill>))}</div>
      <div style={{padding:`0 ${P}px`,display:"flex",flexDirection:"column",gap:14}}>{feedList.map((c,i)=>{const k=`feed-${c.creator.id}-${i}`,oi=c.creator.content.indexOf(c),prod=c.product?PRODUCTS.find(p=>p.id===c.product):null,il=liked[k],cm=cmts[`${c.creator.id}-${oi}`]; return (
        <Cd key={k} style={{padding:0,overflow:"hidden"}}>
          <div style={{display:"flex",alignItems:"center",gap:10,padding:"12px 14px 0"}}><div onClick={e=>{e.stopPropagation();setSel(c.creator)}} style={{width:32,height:32,borderRadius:10,background:C.purple,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",flexShrink:0}}><span style={{fontSize:11,fontWeight:900,color:"#fff"}}>{ini(c.creator.name)}</span></div><div style={{flex:1}} onClick={()=>setSel(c.creator)}><span style={{fontSize:12,fontWeight:700,color:C.text,cursor:"pointer"}}>{c.creator.name}</span><br/><span style={{fontSize:10,color:C.light}}>{c.time} ago</span></div><div style={{display:"flex",gap:4}}><span style={{fontSize:9,fontWeight:800,color:"#fff",background:tcc(c.type),padding:"2px 7px",borderRadius:6}}>{c.type}</span>{c.exclusive&&<span style={{fontSize:9,fontWeight:800,color:C.purple,background:`${C.purple}06`,padding:"2px 7px",borderRadius:6}}>Exklusiv</span>}</div></div>
          <div style={{height:180,margin:"10px 14px 0",borderRadius:12,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center"}}><Eye size={20} color={C.text}/></div>
          <div style={{padding:"12px 14px 14px"}}><h4 style={{fontSize:14,fontWeight:800,color:C.text,margin:"0 0 4px"}}>{c.title}</h4><p style={{fontSize:12,color:C.sub,margin:"0 0 10px",lineHeight:1.5}}>{c.desc}</p>
            {prod&&<div style={{display:"flex",alignItems:"center",gap:8,padding:"8px 10px",borderRadius:10,background:C.soft,marginBottom:10}}><Package size={12} color={C.muted}/><div style={{flex:1}}><div style={{fontSize:11,fontWeight:700,color:C.text}}>{prod.name}</div><div style={{display:"flex",gap:3}}><span style={{fontSize:10,color:C.muted,textDecoration:"line-through"}}>€{prod.price}</span><span style={{fontSize:10,fontWeight:800,color:C.purple}}>€{(parseFloat(prod.price)*(1-parseInt(c.creator.discount)/100)).toFixed(2)}</span></div></div><ShoppingBag size={12} color={C.text}/></div>}
            <div onClick={e=>cp(c.creator.code,e)} style={{display:"inline-flex",alignItems:"center",gap:4,padding:"4px 10px",borderRadius:7,background:`${C.purple}06`,cursor:"pointer",marginBottom:10}}><Percent size={10} color={C.purple}/><span style={{fontSize:11,fontWeight:800,color:C.purple}}>{c.creator.code}</span><span style={{fontSize:9,color:C.muted}}>· {c.creator.discount}</span>{copied===c.creator.code&&<span style={{fontSize:9,color:C.purple}}>✓</span>}</div>
            <div style={{display:"flex",alignItems:"center",gap:3}}><button onClick={e=>tl(k,e)} style={{background:"none",border:"none",cursor:"pointer",display:"flex",alignItems:"center",gap:3,fontSize:11,fontWeight:600,color:il?C.coral:C.muted,padding:"3px 8px 3px 0"}}><Heart size={14} fill={il?C.coral:"none"} color={il?C.coral:C.muted} strokeWidth={1.8}/> {c.likes+(il?1:0)}</button><span style={{display:"flex",alignItems:"center",gap:3,fontSize:11,color:C.muted,padding:"3px 8px"}}><MessageCircle size={13} strokeWidth={1.8}/> {c.comments}</span>{!following[c.creator.id]&&<button onClick={e=>tf(c.creator.id,e)} style={{marginLeft:"auto",padding:"4px 10px",borderRadius:7,border:"none",background:C.purple,color:"#fff",fontSize:10,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>Follow</button>}</div>
            {cm&&<div style={{marginTop:8,padding:"8px 10px",borderRadius:8,background:C.soft,fontSize:11}}><span style={{fontWeight:700,color:C.text}}>{cm.u}</span> <span style={{color:C.sub}}>{cm.t}</span></div>}
          </div>
        </Cd>);})}</div>
    </div></div>
  );
}

function Profile({points,onReferral}){
  const lvl=LEVELS.reduce((a,l)=>points>=l.min?l:a,LEVELS[0]);const next=LEVELS[LEVELS.indexOf(lvl)+1];const pct=next?(points-lvl.min)/(next.min-lvl.min):1;const[tab,setTab]=useState("badges");const eb=BADGES.filter(b=>b.earned).length;
  const rewards=[{n:"Free Shipping",c:300,i:Truck},{n:"10% Discount",c:500,i:Percent},{n:"Mystery Box",c:1500,i:Gift},{n:"VIP Event",c:3000,i:Calendar},{n:"Brand Dinner",c:5000,i:Award}];
  const activity=[{t:"Review geschrieben",pts:"+50",time:"2h",icon:Star},{t:"Badge: Amplifier",pts:null,time:"1d",icon:Award},{t:"Produkt geteilt",pts:"+30",time:"2d",icon:Share2},{t:"Level Up",pts:null,time:"5d",icon:Zap}];
  const tabs=[{id:"badges",l:"Badges"},{id:"rewards",l:"Rewards"},{id:"activity",l:"Activity"},{id:"settings",l:"Settings"}];

  return (
    <div style={{paddingBottom:80,position:"relative"}}><Bg v="profile"/><div style={{position:"relative",zIndex:1}}>
      <div style={{padding:`32px ${P}px 0`,display:"flex",alignItems:"center",gap:16}}><Ring size={76} sw={5} pct={pct}><div style={{width:54,height:54,borderRadius:18,background:C.purple,display:"flex",alignItems:"center",justifyContent:"center"}}><Crown size={24} color="#fff" strokeWidth={1.5}/></div></Ring><div style={{flex:1}}><h2 style={{fontSize:18,fontWeight:900,color:C.text,margin:0}}>{lvl.name}</h2><div style={{fontSize:24,fontWeight:900,color:C.text,lineHeight:1}}>{points} <span style={{fontSize:12,fontWeight:600,color:C.muted}}>pts</span></div>{next&&<p style={{fontSize:11,color:C.muted,fontWeight:600,margin:"3px 0 0"}}>{next.min-points} bis {next.name}</p>}</div></div>
      <div style={{display:"flex",gap:8,padding:`16px ${P}px 0`}}>{[{l:"Reviews",v:"4"},{l:"Badges",v:`${eb}/${BADGES.length}`},{l:"Streak",v:"3d"},{l:"Shares",v:"7"}].map((s,i)=>(<div key={i} style={{flex:1,padding:"10px 6px",borderRadius:12,background:C.card,boxShadow:C.sh,textAlign:"center"}}><div style={{fontSize:16,fontWeight:900,color:C.text}}>{s.v}</div><div style={{fontSize:9,fontWeight:700,color:C.muted}}>{s.l}</div></div>))}</div>
      <div style={{display:"flex",borderBottom:`1px solid ${C.border}`,padding:`16px ${P}px 0`}}>{tabs.map(t=>(<button key={t.id} onClick={()=>setTab(t.id)} style={{flex:1,padding:"10px 0",background:"none",border:"none",borderBottom:tab===t.id?`2px solid ${C.purple}`:"2px solid transparent",fontSize:12,fontWeight:700,color:tab===t.id?C.text:C.muted,cursor:"pointer",fontFamily:"inherit"}}>{t.l}</button>))}</div>
      <div style={{padding:`14px ${P}px`}}>
        {tab==="badges"&&BADGES.map(b=>(<div key={b.id} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 0",borderBottom:`1px solid ${C.border}`,opacity:b.earned?1:.4}}><div style={{width:42,height:42,borderRadius:12,background:b.earned?`${C.purple}08`:C.soft,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><b.icon size={18} color={b.earned?C.purple:C.light} strokeWidth={1.5}/></div><div style={{flex:1}}><div style={{fontSize:13,fontWeight:700,color:C.text}}>{b.name}</div>{b.earned?<div style={{fontSize:11,color:C.purple,fontWeight:600}}>Verdient</div>:<div style={{fontSize:11,color:C.muted}}>{b.hint}</div>}</div>{b.earned?<Check size={16} color={C.purple}/>:<Lock size={13} color={C.light}/>}</div>))}
        {tab==="rewards"&&(<div style={{position:"relative",paddingLeft:16}}><div style={{position:"absolute",left:6,top:0,bottom:0,width:2,background:C.soft,borderRadius:1}}/><div style={{position:"absolute",left:6,top:0,width:2,borderRadius:1,background:C.purple,height:`${Math.min((points/5000)*100,100)}%`}}/>
          {rewards.map((rw,i)=>{const ok=points>=rw.c,isN=!ok&&(i===0||points>=rewards[i-1].c); return (<div key={i} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 0",position:"relative"}}><div style={{position:"absolute",left:-12,width:14,height:14,borderRadius:7,background:ok?C.purple:isN?C.card:C.soft,border:ok?"none":`2px solid ${isN?C.purple:C.border}`,display:"flex",alignItems:"center",justifyContent:"center",zIndex:1}}>{ok&&<Check size={8} color="#fff" strokeWidth={3}/>}{isN&&<div style={{width:5,height:5,borderRadius:3,background:C.purple}}/>}</div><Cd style={{flex:1,padding:12}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><div><div style={{fontSize:13,fontWeight:700,color:C.text}}>{rw.n}</div><div style={{fontSize:11,color:C.muted}}>{rw.c} pts</div></div>{ok&&<Btn small>Einlösen</Btn>}{isN&&<span style={{fontSize:11,fontWeight:700,color:C.purple}}>{rw.c-points} pts</span>}{!ok&&!isN&&<Lock size={13} color={C.light}/>}</div></Cd></div>);})}</div>)}
        {tab==="activity"&&activity.map((a,i)=>{const AI=a.icon; return (<div key={i} style={{display:"flex",alignItems:"center",gap:11,padding:"11px 0",borderBottom:i<activity.length-1?`1px solid ${C.border}`:"none"}}><div style={{width:34,height:34,borderRadius:10,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><AI size={15} color={C.purple} strokeWidth={1.8}/></div><div style={{flex:1}}><div style={{fontSize:12,fontWeight:600,color:C.text}}>{a.t}</div><div style={{fontSize:10,color:C.light}}>{a.time} ago</div></div>{a.pts&&<span style={{fontSize:12,fontWeight:800,color:C.purple}}>{a.pts}</span>}</div>);})}
        {tab==="settings"&&(<div>{[{l:"Account",s:"E-Mail, Passwort",i:Crown},{l:"Freunde einladen",s:"200 pts verdient",i:Gift,action:onReferral},{l:"Benachrichtigungen",s:"Push, E-Mail",i:Sparkles},{l:"Partner",s:"Alex · Verbunden",i:Heart},{l:"Datenschutz",s:"Sichtbarkeit",i:Lock}].map((s,i)=>(<div key={i} onClick={s.action||undefined} style={{display:"flex",alignItems:"center",gap:11,padding:"12px 0",borderBottom:i<4?`1px solid ${C.border}`:"none",cursor:"pointer"}}><div style={{width:34,height:34,borderRadius:10,background:C.soft,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><s.i size={15} color={C.sub} strokeWidth={1.6}/></div><div style={{flex:1}}><div style={{fontSize:12,fontWeight:600,color:C.text}}>{s.l}</div><div style={{fontSize:11,color:C.muted}}>{s.s}</div></div><ChevronRight size={13} color={C.light}/></div>))}</div>)}
      </div>
    </div></div>
  );
}

export default function App(){
  const[screen,setScreen]=useState("home");const[points,setPoints]=useState(320);const[notifOpen,setNotifOpen]=useState(false);const[onboarded,setOnboarded]=useState(false);const unreadCount=NOTIFS.filter(n=>!n.read).length;
  const css=`@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800;900&display=swap');*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent}body{background:${C.bg}}::-webkit-scrollbar{width:0;height:0}@keyframes fi{from{opacity:0}to{opacity:1}}@keyframes pop{from{transform:scale(.7);opacity:0}to{transform:scale(1);opacity:1}}input::placeholder,textarea::placeholder{color:${C.muted}}`;
  if(!onboarded) return (<div style={{maxWidth:430,margin:"0 auto",minHeight:"100vh",background:C.bg,fontFamily:"'Plus Jakarta Sans',-apple-system,sans-serif"}}><style>{css}</style><Onboarding onDone={()=>setOnboarded(true)}/></div>);
  return (
    <div style={{maxWidth:430,margin:"0 auto",minHeight:"100vh",background:C.bg,fontFamily:"'Plus Jakarta Sans',-apple-system,sans-serif"}}><style>{css}</style>
      {screen==="home"&&<Home points={points} go={setScreen} onNotif={()=>setNotifOpen(true)} unreadCount={unreadCount}/>}
      {screen==="earn"&&<Earn points={points} addPoints={n=>setPoints(p=>p+n)}/>}
      {screen==="couple"&&<Couple/>}
      {screen==="community"&&<Community/>}
      {screen==="creators"&&<CreatorsScreen/>}
      {screen==="events"&&<Home points={points} go={setScreen} onNotif={()=>setNotifOpen(true)} unreadCount={unreadCount}/>}
      {screen==="profile"&&<Profile points={points} onReferral={()=>setScreen("referral")}/>}
      {screen==="referral"&&<Referral onBack={()=>setScreen("profile")}/>}
      <Nav active={screen} go={setScreen}/>
      <NotifPanel open={notifOpen} onClose={()=>setNotifOpen(false)} onNav={setScreen}/>
    </div>
  );
}